### ISSUE TITLE
Employee being matched with service accounts (HELP!!!)

### ISSUE THREAD

**Issue by RobCRees** [OfficeDev/microsoft-teams-apps-icebreaker#100]
How do we prevent icebreaker from pairing an employee with a service account?  Is there a way to use a security group to 
"pull" valid employees for matching?

Please help...

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
