### ISSUE TITLE
Getting Error while step2 deploying to azure

### ISSUE THREAD

**Issue by rstarzy** [OfficeDev/microsoft-teams-apps-icebreaker#101]
We're getting error

The current subscription type is not permitted to perform operations on any provider namespace. Please use a different subscription.

Not sure what is the problem, do we need another subscription?

Thanks

**Comment by lostdoco** [comment]
hi @rstarzy - it looks like that subscription has no providers registered. You would need to have the owner role to register providers for that subscription. Do you have another subscription you can try?

**Comment by rstarzy** [comment]
Hi thanks for answer, unfortunately we don't have another subscription. I will talk to our purchase dep maybe they can order some subscripton and we can test.
