### ISSUE TITLE
App Registration

### ISSUE THREAD

**Issue by vineet2907** [OfficeDev/microsoft-teams-apps-icebreaker#102]
I understand that the Azure app needs to be registered as a multi-tenant app because we are doing a manual app registration. However most organisations have tight security control policies when it comes to deploying multi-tenant apps in Azure. Most of them do not even allow deploying multi-tenant apps. Is there any way (or a workaround) this app can be deployed as a single-tenant app?

**Comment by gtageek** [comment]
We have the same concern as vineet2907. Our enterprise security policy does not allow us to setup apps in the multi-tenant mode.
Will the Icebreaker app work if we set it up in the single-tenant mode, i.e., if we select "Accounts in this organizational directory only?"

**Comment by SubbaReddi** [comment]
It will not work with single tenant option. Similar reference here: https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Frequently-Asked-Questions-(FAQ)#is-it-mandatory-to-choose-multi-tenant-account-types-while-app-registration
