### ISSUE TITLE
Cannot upload to Teams, general error

### ISSUE THREAD

**Issue by ghost** [OfficeDev/microsoft-teams-apps-icebreaker#105]
Made the edits to manifest still not uploading. Anyone help me out please?

![image](https://user-images.githubusercontent.com/61513864/96730688-14287400-137c-11eb-8dbe-4ad62fb25d57.png)

**Comment by dfarrisVMED** [comment]
Additional info, i user app studio to validate the app, fails for small icon
![image](https://user-images.githubusercontent.com/61513864/96735825-936c7680-1381-11eb-9598-1e7f68f5940d.png)

**Comment by simonleray-meyer** [comment]
Hi,

Thanks for the tip on using App Studio, that helped me work out what the issue was.

I just resized the small icon using MSPaint from the 20x20 pixels it comes with in the package to 32x32 and sorted.

regards

Simon
