### ISSUE TITLE
Can't upload to Teams

### ISSUE THREAD

**Issue by Julie-Vandehey** [OfficeDev/microsoft-teams-apps-icebreaker#107]
Tried two fixes:

Resized Manifest Color .png to 20x20 pixels - error
Resized Manifest color.GIF to 20x20 pixels - Error

neither worked.  New to github.  Trying to bring downloaded file in Microsoft Teams

**Comment by Rutger-Knijnenburg** [comment]
Hi!

Have you checked the URL paramters in the manifest.json? They need to contain https:// and shouldn't start with www.
You could try the App Studio app from Microsoft to identify your issue.

Follow these steps to add the App Studio to your Teams environment, then use the validator to check for manifest errors:
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/app-studio-overview

**Comment by SPTstephan** [comment]
i have the same problem:
cant upload as admin in teams admin center and the app studio shows me the errors:
![image](https://user-images.githubusercontent.com/77100427/104006713-29f14c80-51a7-11eb-8653-7343e22a606f.png)

**Comment by Rutger-Knijnenburg** [comment]
> i have the same problem:
> cant upload as admin in teams admin center and the app studio shows me the errors:
> ![image](https://user-images.githubusercontent.com/77100427/104006713-29f14c80-51a7-11eb-8653-7343e22a606f.png)
> 

You need to change the icon size of the image in the manifest folder. The size needs to be 32x32 pixels.

**Comment by Rutger-Knijnenburg** [comment]
Hi @SPTstephan,

Make sure you the size of the icon (outline.png) is set to 32x32 pixels.
It's the same issue+fix descripted in issue #105 .
