### ISSUE TITLE
Can deploy add as a global app

### ISSUE THREAD

**Issue by ghost** [OfficeDev/microsoft-teams-apps-icebreaker#108]
Cannot add to just a single team. Error only team organizers can add to tab?
<img width="549" alt="only meeting organizers" src="https://user-images.githubusercontent.com/61513864/97587802-cd64fa80-19c9-11eb-8c60-0de7e7dbdc07.PNG">

**Comment by PramodDeokar-ms** [comment]
Hi
Can you please share more details or repro steps. Thanks

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
