### ISSUE TITLE
Group IceBreaker

### ISSUE THREAD

**Issue by MaggiMartens** [OfficeDev/microsoft-teams-apps-icebreaker#109]
Hi Devs, 
i'd like to ask whether there is an easy way to configure Group Setups instead of 1:1. I searched the code a little bit but couldn't find any settings. We think it might be a cool idea to have the option to set the amount of people that get pushed into a meeting. 
Would be happy about any feedback :) thanks for this great app anyway!

**Comment by PramodDeokar-ms** [comment]
For this microsoft-teams-apps-icebreaker repository, we are currently only making changes to fix critical bugs or deployment failures. Please consider forking the repository to implement your improvement and post back here if you're successful.

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
