### ISSUE TITLE
Troubleshooting

### ISSUE THREAD

**Issue by RichardSaouma** [OfficeDev/microsoft-teams-apps-icebreaker#110]
Howdy,

RESOLVED; however there are a growing handful of additional questions surfaced in your techcommunity guide here:

https://techcommunity.microsoft.com/t5/microsoft-teams-blog/icebreaker-bot-assisted-happenstance-to-strengthen-your-company/ba-p/722552

Any and all assistance is greatly appreciated, thank you!

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
