### ISSUE TITLE
Disable "Pause all matches"

### ISSUE THREAD

**Issue by tonycheun123** [OfficeDev/microsoft-teams-apps-icebreaker#113]
When the number of members in the channel is odd, one member would be left out the pairing.
Is it possible to disable "Pause all matches"?

**Comment by SubbaReddi** [comment]
When the number of members in the channel is odd, one member would be left out the pairing.: **Yes, you are right**
Is it possible to disable "Pause all matches"?: Logic app runs weekly once to send matches. Disable the logic app to pause all matches.
