### ISSUE TITLE
Not pairing everyone (Specsavers)

### ISSUE THREAD

**Issue by Ticky321** [OfficeDev/microsoft-teams-apps-icebreaker#114]
Dear GitHub,

We implemented the Ice-Breaker bot in November 2020 to a trial group of 40 people. The bot was scheduled to deploy on the following Tuesday at 10.00am which it did, but the log reported there were six errors, i.e. did not pair 6 people. Unfortunately, the bot does not provide any additional information as to why it failed. Since then, we have had ongoing issues with the bot not always sending an invite or sending the invite, but only to one of the pairs matched. 

We followed the deployment instructions on GitHub and therefore cannot understand why it's not working 100% of the time. Can anyone help or advise?

**Comment by PramodDeokar-ms** [comment]
@Ticky321 Please share error log details from application Insights
