### ISSUE TITLE
Lost the configuration parameters in Recurrence after switching to every hour

### ISSUE THREAD

**Issue by ninagarcia** [OfficeDev/microsoft-teams-apps-icebreaker#115]
I went into the Logic Apps Designer to switch settings in order to test more quickly. After setting to every hour, when I switch back to weekly or monthly, the day and hour parameters are missing. I could put these into the code directly but not sure where to get them from in the source code.

{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "HTTP": {
                "inputs": {
                    "method": "GET",
                    "uri": "https://icebreaker-xxx"
                },
                "runAfter": {},
                "type": "Http"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "parameters": {},
        "triggers": {
            "Recurrence": {
                "recurrence": {
                    "frequency": "Month",
                    "interval": 1,
                    "timeZone": "UTC"
                },
                "type": "Recurrence"
            }
        }
    },
    "parameters": {}
}

**Comment by SubbaReddi** [comment]
It could be too late response.
If you still looking for response, Here are the options to choose additional parameters
![image](https://user-images.githubusercontent.com/69682598/124907812-36dfe300-e006-11eb-9170-c037d167564b.png)

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
