### ISSUE TITLE
deployment failure - Write Sourcecontrols

### ISSUE THREAD

**Issue by SPTstephan** [OfficeDev/microsoft-teams-apps-icebreaker#116]
in the deployment steps i get a failure:
Write Sourcecontrols - failure - ResourceDeploymentFailure
icebreaker-tqg65rkodba4o/web - Microsoft.Web/sites/sourcecontrols 
![image](https://user-images.githubusercontent.com/77100427/103878355-98b2a500-50d6-11eb-946d-c674b3539f10.png)

i need help because i have already been tested a other ressource group, other location north europa and usa west 2, other payment.

**Comment by beauzeaux** [comment]
@SPTstephan thanks for the report. I had changed the default branch name and forgotten to update the ARM template. 

This should be fixed here shortly but in the interim you can replace the default 'gitBranch' in the deployment with 'main' instead of 'master'
