### ISSUE TITLE
Need help for IceBreaker integrated in MS Teams

### ISSUE THREAD

**Issue by Munavvar-Husein** [OfficeDev/microsoft-teams-apps-icebreaker#119]
Hello Experts,

It is really a great idea for a IceBreaker Bot! Really loved the concept of the tool. We have installed and it is working perfectly. But we are having few queries for the same.

> In this link we found the idea of Leaderboard. This idea is really great. Is the solution of Leaderboard available anywhere?
https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/wiki/Taking-it-further

> We have found that there are two tables in Azure Cosmos DB. Whether additional data is stored anywhere? Like Total No of matches, Users who accepted the match etc.

Your response will be highly appreciated.

**Comment by Rutger-Knijnenburg** [comment]
Hi @Munavvar-Husein ,

The Leaderboard idea is just a concept idea without a working solution attached, you'll have to create it by yourself.
Out of the box this app includes a 'recent pair ups' property. The solution, as far as I can tell, doesn't use this property. You could extend the solution by appending this property with recent pair ups and thereby creating a list of pairups. 

I hope this answers your question.

**Comment by Munavvar-Husein** [comment]
Hi @Rutger-Knijnenburg 

Thank you for your response.

Yes we got our answers and we will start implementing the same.

**Comment by Rutger-Knijnenburg** [comment]
Great :) Don't forget to close this issue if you no longer require help.

**Comment by Munavvar-Husein** [comment]
Sure. We will close the issue.

Thank you @Rutger-Knijnenburg
