### ISSUE TITLE
Uploading app to Teams issue

### ISSUE THREAD

**Issue by gavinbeere1** [OfficeDev/microsoft-teams-apps-icebreaker#122]
Hi Guys,

I have been in touch with Microsoft Support regarding this Icebreaker app. They have advised to reach out to the developers as there is an issue on both my end and their end when uploading. I have attached this error.

Could you advise the steps needed to be able to upload this app? Thanks

![Gavin1](https://user-images.githubusercontent.com/33692090/105508101-e37e1080-5cc3-11eb-94c9-2d2d0eeb77da.PNG)

**Comment by AzureRPDEV** [comment]
Hi @gavinbeere1 ,

Could you try validating the JSON with the 'App Studio' in Teams?

Follow these steps to add the App Studio to your Teams environment, then use the validator to check for manifest errors:
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/app-studio-overview

**Comment by Rutger-Knijnenburg** [comment]
Hi @gavinbeere1  ,

Could you try validating the JSON with the 'App Studio' in Teams?

Follow these steps to add the App Studio to your Teams environment, then use the validator to check for manifest errors:
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/app-studio-overview

**Comment by gavinbeere1** [comment]
Hi Rutger,

So I ran the .zip package through the validator and it failed with the below error code:

![image](https://user-images.githubusercontent.com/33692090/105706746-d9e5ea00-5f09-11eb-95d1-65577a14185f.png)

I have also attached the .zip package too.

[Icebreaker.zip](https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/files/5866546/Icebreaker.zip)

Let me know the next steps, thank you!

**Comment by Rutger-Knijnenburg** [comment]
Hi @gavinbeere1 ,

Please update the manifest.json with the correct and valid privacyURL and termsofUseURL.
This should include 'https://' and shouldn't start with www.

**Comment by gavinbeere1** [comment]
Hi there,

Thank you! That worked for me!

Kind regards,

**Comment by Rutger-Knijnenburg** [comment]
@gavinbeere1 Don't forget to close the report if it's still working :)
