### ISSUE TITLE
Exclude a user

### ISSUE THREAD

**Issue by belasor** [OfficeDev/microsoft-teams-apps-icebreaker#123]
Hello,

We´re currently facing the issue, that we have a technical User in the team. 
We don´t want that anyboy is getting matched with the user.

Is there a way to exclude a user from the matching?

BR

**Comment by arifC** [comment]
For those still looking for a solution to exclude a user. You can use the data explorer in the Cosmos DB resource to exclude a certain user. Just add the user to the table "UserOptinStatus":
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/11600883/107851534-073bfe80-6e0b-11eb-80da-30683b673c3c.png)
