### ISSUE TITLE
Unauthorized Error - 500

### ISSUE THREAD

**Issue by dariovarzea** [OfficeDev/microsoft-teams-apps-icebreaker#124]
Hello, upon deploying Icebreaker all i get is the following 

{
    "statusCode": 500,
    "headers": {
        "Pragma": "no-cache",
        "Request-Context": "appId=cid-v1:4e754aec-558d-4e2e-99b2-20ff67dbc739",
        "Access-Control-Expose-Headers": "Request-Context",
        "Cache-Control": "no-cache",
        "Set-Cookie": "ARRAffinity=65f634b3cbf2630e5599d9028e59ac832794a9c57ae50a1a9655757a4f209c6b;Path=/;HttpOnly;Secure;Domain=icebreaker-taofmseczr55o.azurewebsites.net,ARRAffinitySameSite=65f634b3cbf2630e5599d9028e59ac832794a9c57ae50a1a9655757a4f209c6b;Path=/;HttpOnly;SameSite=None;Secure;Domain=icebreaker-taofmseczr55o.azurewebsites.net",
        "Server": "Microsoft-IIS/10.0",
        "X-AspNet-Version": "4.0.30319",
        "X-Powered-By": "ASP.NET",
        "Date": "Tue, 26 Jan 2021 13:16:57 GMT",
        "Content-Length": "2817",
        "Content-Type": "application/json; charset=utf-8",
        "Expires": "-1"
    },
    "body": {
        "message": "An error has occurred.",
        "exceptionMessage": "Unauthorized",
        "exceptionType": "Microsoft.Bot.Connector.MicrosoftAppCredentials+OAuthException",
        "stackTrace": "   at Microsoft.Bot.Connector.MicrosoftAppCredentials.<RefreshTokenAsync>d__34.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Connector.MicrosoftAppCredentials.<GetTokenAsync>d__27.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Icebreaker.Controllers.ProcessNowController.<Get>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()",
        "innerException": {
            "message": "An error has occurred.",
            "exceptionMessage": "Response status code does not indicate success: 401 (Unauthorized).",
            "exceptionType": "System.Net.Http.HttpRequestException",
            "stackTrace": "   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()\r\n   at Microsoft.Bot.Connector.MicrosoftAppCredentials.<RefreshTokenAsync>d__34.MoveNext()"
        }
    }
}

I can add it to teams but nothing happens after that. Any help would be greatly appreciated. 

Added the manifesto details also

{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.3/MicrosoftTeams.schema.json",
  "manifestVersion": "1.3",
  "version": "1.0.0",
  "id": "d55d08d9-bacb-4567-942f-afd85d632dcc",
  "packageName": "com.microsoft.teams.icebreaker",
  "developer": {
    "name": "PKF Francis Clark LLP",
    "websiteUrl": "https://thoughstuff.com",
    "privacyUrl": "https://www.thoughstuff/policies/",
    "termsOfUseUrl": "https://www.thoughstuff/policies/"
  },
  "icons": {
    "color": "color.png",
    "outline": "outline.png"
  },
  "name": {
    "short": "Icebreaker"
  },
  "description": {
    "short": "Icebreaker is a bot that randomly pairs team members up to build team unity.",
    "full": "Icebreaker is a little bot that randomly pairs team members up every week to help the team build trust and personal connections."
  },
  "accentColor": "#64A2CC",
  "bots": [
    {
      "botId": "d4c4aae4-19aa-468f-8508-987aad9b2d17",
      "scopes": [
        "personal",
        "team"
      ],
      "supportsFiles": false,
      "isNotificationOnly": true
    }
  ],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "icebreaker-taofmseczr55o.azurewebsites.net"
  ]
}

**Comment by kbedard8668** [comment]
I'm running into the same problem. Did you happen to find a resolution for this issue?

Also, do you have a 3rd party auth service like Okta?

Thanks,
Kim

**Comment by SubbaReddi** [comment]
Please confirm whether you selected multi tenant option or not in app registration?
![image](https://user-images.githubusercontent.com/69682598/124908590-195f4900-e007-11eb-83be-fde8529f94ab.png)

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
