### ISSUE TITLE
Modifying Bot parameters

### ISSUE THREAD

**Issue by gavinbeere1** [OfficeDev/microsoft-teams-apps-icebreaker#125]
Hi there!

I have successfully implemented the bot, but am unsure of how I can test it, as I cant remember what I initially set the bots time to match for.

Is there a way I can actively change this without having to reupload the app?

**Comment by shridharp-ms** [comment]
Please refer: https://blog.thoughtstuff.co.uk/2019/07/how-to-adjust-the-pairing-schedule-of-the-icebreaker-bot-teams-app-template/
