### ISSUE TITLE
Resume Matches when the Chat has been purged

### ISSUE THREAD

**Issue by leeschmidgall** [OfficeDev/microsoft-teams-apps-icebreaker#127]
Hello -

We have a user who paused matches, and our policy purged the message from Icebreaker.  However, now that user wants to reconnect, but is unable to do so.  Is there a link to activate or a way to allow them to opt back in?

**Comment by apleitch** [comment]
+1 I have the same issue.  Un-pause link is in chat and chats are cleaned up by our data retention policy so I can't see how to un-pause the user.

**Comment by apleitch** [comment]
was able to un-pause behind the scenes by editing "UserOptinStatus" as per this https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/issues/123
