### ISSUE TITLE
How do I get to know the mapping logic used for this App

### ISSUE THREAD

**Issue by DipanjanGhosh85** [OfficeDev/microsoft-teams-apps-icebreaker#128]
We have to identify the random matching logic used for the matching as we need to tweak it a little as per our business needs. Which are the files or where are the files for the same .

**Comment by cagrimunyas** [comment]
I have the same request for my customer. Pairing function is [here](https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/blob/8dd87c62606b94efbdfdb440365166809c492733/Source/Icebreaker/IcebreakerBot.cs#L405). In the same file(of the bot itself) you can find most of the associated functions with pairing.

**Comment by DipanjanGhosh85** [comment]
Thanks for your response it helped a lot .
Had one more question how are you redeploying the source code that you modified to reflect in the app in Teams ?

**Comment by v-smahaj** [comment]
@DipanjanGhosh85 : There are two ways to achieve this:
1. You can do a fresh deployment and enter updated path (with modified code) in ARM template.
2. If you want to reuse existing resources, go to App Service in Azure portal => Go to deployment center => Click on Disconnect => Add your new deployment location to App Service.
3. If you have taken you code in local, download Publish Profile from App Service and publish code from Visual Studio.

If you are following steps 2 or 3, you dont need to upload app again in Teams. Existing app with reflect latest changes.
Let us know in case of any queries.
Thanks!
