### ISSUE TITLE
Pairing not triggering in teams, Logic app is working fine and successful. but no triggers in teams

### ISSUE THREAD

**Issue by Nandeesh82** [OfficeDev/microsoft-teams-apps-icebreaker#136]
Hi Team,

we have deployed icebreaker bot into teams, after all azure resources deployed in portal. Logic app is working fine and successful triggering as per schedule. but no alerts in teams. How to debug or what could be issue.

**Comment by Nandeesh82** [comment]
@salaman we have deployed icebreaker bot into teams, after all azure resources deployed in portal. Logic app is working fine and successful triggering as per schedule. but no alerts in teams. How to debug or what could be issue.

**Comment by wy62** [comment]
Hi @Nandeesh82, did you manage to find a solution to this issue? I am having the same problem and have not yet found a solution.

**Comment by Nandeesh82** [comment]
> Hi @Nandeesh82, did you manage to find a solution to this issue? I am having the same problem and have not yet found a solution.

@wy62 , It is working fine now. Check your manifest package and app Id details. Mine was a network configuration issue. If no changes to gitub code, Then it should work fine.

**Comment by wy62** [comment]
I've checked the manifest file multiple times. All looks ok.

Can you be more specific about your network configuration issue?

I'm pulling my hair out with this!

**Comment by Nandeesh82** [comment]
@wy62 , Mine was network configuration issue, which I have done as per organization settings, firewall was blocking and configured it with Vnet and Subnet details. 
but I have configured the same GitHub bot in my subscription without any issues, here I have not done any changes to Network.

**Comment by wy62** [comment]
@Nandeesh82 Thanks for your help. I finally managed to get this working today. The problem was that we had deployed the app to one tenant but it would be used in a different tenant. So when deploying the app I had to change the tenant ID to the tenant where the app was going to be used.
