### ISSUE TITLE
Duplicate cards

### ISSUE THREAD

**Issue by WilliamJYoung** [OfficeDev/microsoft-teams-apps-icebreaker#137]
Hi! I recently installed the bot in a new Team and added 5 other accounts. It worked but on my own account, I was getting duplicate cards. I re-ran the logic app and it then matched all 6 accounts with exactly the same pairings. I ran it again and it matched me once but another pair twice. Next time it matched me twice to 2 different accounts. I then deleted the Team, created a new one and added 2 other accounts and the bot. It now matched me twice to different accounts, including one that isn't in the Team.

**It looks like I need a way to clear the user accounts from the bot.** It's probably got some in twice somehow
I assume this is a CosmosDB thing but can't see where.
Can anyone advise, please?
Thanks

**Comment by WilliamJYoung** [comment]
I think its now working. It seems that we have to remove the old Teams manually

![AzureCosmos](https://user-images.githubusercontent.com/15154437/108835987-30594d80-75c8-11eb-914d-813831195ce4.png)

**Comment by Rutger-Knijnenburg** [comment]
Hi! I have the exact same issue. The welcome card is send twice.
I've also tried removing all teams manually from Cosmos, without any luck. 

Could you report back in a few days if it's still working? I'm curious, because I suspect some caching mechanism....

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
