### ISSUE TITLE
Disable "Propose meetup" option

### ISSUE THREAD

**Issue by danworldinc** [OfficeDev/microsoft-teams-apps-icebreaker#138]
Hi, our organization has not deployed Microsoft Outlook as we still use Google Calendar.  Is it possible to configure the Icebreaker Bot to disable to the "Propose meetup" option so that users don't see it.  Best case scenario would be to have it use Google Calendar, but I know that would like take a lot of customization.  At this point, we be happy with just hiding the button.

Any suggestions or solutions for that?

**Comment by SrivatsanVasudevan** [comment]
You will have to make some changes in the files PairUpNotificationAdaptiveCard.cs and PairUpNotificationAdaptiveCard.json.

In the PairUpNotificationAdaptiveCard.cs file, comment or delete line 57, which gets the propose meetup button text.

In the PairUpNotificationAdaptiveCard.json file, comment or delete lines 54 to 58, which create the actual button for propose meetup for the Icebreaker app.

You will have to make these changes in a forked copy of the Icebreaker app, Once you've pushed these changes, then start the manual deployment process of the Icebreaker app, and in step 2, when deploying to Azure, ensure that the field pointing to the Icebreaker Github repo is not pointing to https://github.com/OfficeDev/microsoft-teams-apps-icebreaker and is instead pointing to the forked repo where you have made the required changes.

![githubrepo](https://user-images.githubusercontent.com/29865459/111892054-03287100-89b5-11eb-9f33-fa00b19a7883.png)


Then follow the remaining steps, and you will then have the Icebreaker app deployed without the propose meetup button.

**Comment by PramodDeokar-ms** [comment]
For this microsoft-teams-apps-icebreaker repository, we are currently only making changes to fix critical bugs or deployment failures. Please consider forking the repository to implement your improvement and post back here if you're successful.
