### ISSUE TITLE
Icebreaker can't be added due to an issue with the bot

### ISSUE THREAD

**Issue by chrish7** [OfficeDev/microsoft-teams-apps-icebreaker#143]
Getting this error while adding Icebreaker to Teams "Icebreaker can't be added due to an issue with the bot"
Any suggestions here..

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
