### ISSUE TITLE
Bot User display name

### ISSUE THREAD

**Issue by CorinaLancheros** [OfficeDev/microsoft-teams-apps-icebreaker#144]
Hello.,
I will like to change the display name for the Bot User . Currently we get the cards from **Bot User - 2b57bc41-596...**.and will like it so show as "IceBreaker Virtual Admin" instead.  But, I cannot find any documentation on how to do it.  Is it possible and do you know how?

Thank you! 
Corina

**Comment by Rutger-Knijnenburg** [comment]
Hi Corina!

There are two places you should change the display name to be sure it's uniform across all channels.

- Bot resource on Azure (go to settings, you will see a display name property over there)
- Inside the manifest's json that is included in the package that should be uploaded to Teams. Here you will also follow find a name property.

If you need further help, please say so! Happy to help you :)
