### ISSUE TITLE
How can I go about Branding or adding our company logo to our icebraker 

### ISSUE THREAD

**Issue by CorinaLancheros** [OfficeDev/microsoft-teams-apps-icebreaker#145]
We will like to add a logo and perhaps change the color scheme on Icebreaker.  Do you have any instructions on how to go about doing this?
Thank you,
Corina

**Comment by SrivatsanVasudevan** [comment]
You will have to replace the color.png and outline.png files in the manifest folder with your new logos, using the same file names. The color.png file should be of size 192x192 and outline.png should be a transparent logo of size 32x32, which will go in the left rail of Teams. You can also change the name of the bot and the description in the manifest.json file. Once you have made the required changes to the 3 files, you will have to sideload the app again with the above changes.

In Azure, navigate to the resource group where you deployed the Icebreaker and select the web app bot resource. In the settings section, you will have the option to change the logo and the name. Update the logo with the 32x32 image.

Similarly, you can change the accentColor in the manifest file to change the color scheme of the Icebreaker app.

**Comment by CorinaLancheros** [comment]
Hi,
Thank you so much we will take care of that.
About the name, I do see under the manifest.json file this


  "name": {
    "short": "Icebreaker"
  },


But when pairing and people get a card it shows as coming from "Bot User 2b57bc41-596f-41da-8f9c-8411f1e3f6c0 " instead of "Icebreaker".  I will change the name to what I want and see what happens.

Thank you again,
Corina
