### ISSUE TITLE
individual pairing settings for each channel

### ISSUE THREAD

**Issue by markusd1984** [OfficeDev/microsoft-teams-apps-icebreaker#146]
Would it be possible to change the pairing settings for each icebreaker channel individually and right in the channel?

Otherwise one would have to deploy an icebreaker for each team/channel where different settings are required.

https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/issues/95
https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/issues/67
https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/issues/80

**Comment by PramodDeokar-ms** [comment]
For this microsoft-teams-apps-icebreaker repository, we are currently only making changes to fix critical bugs or deployment failures. Please consider forking the repository to implement your improvement and post back here if you're successful.

**Comment by markusd1984** [comment]
Good to know, thanks.

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!

**Comment by markusd1984** [comment]
I'd recommend implementing it if someone's has the skills and time, I'm sure many regular users would benefit.

**Comment by v-royavinash** [comment]
@markusd1984 We have added the feature/enhancement request to our backlog items. We will be taking it in our future releases depending upon the priority and bandwidth. For now, we are marking this request closed.

**Comment by markusd1984** [comment]
> @markusd1984 We have added the feature/enhancement request to our backlog items. We will be taking it in our future releases depending upon the priority and bandwidth. For now, we are marking this request closed.

Many thanks, does this mean that there is still some life in the support and Dev roadmap for this kind of keyboard in coming months/year?

Logitech had a huge opportunity to disrupt the keyboard market especially for professional with workflow related apps.
