### ISSUE TITLE
Welcome and pairing message in specific channels instead of GENERAL

### ISSUE THREAD

**Issue by markusd1984** [OfficeDev/microsoft-teams-apps-icebreaker#147]
would be great if this were possible, to use existing teams as supposed to creating teams just for the icebreaker bot purpose.

https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/pull/6

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
