### ISSUE TITLE
Question - Is it possible to add the Icebreaker App to Yammer?

### ISSUE THREAD

**Issue by chicago-dev-ui** [OfficeDev/microsoft-teams-apps-icebreaker#148]
We are looking to also driving adoption of Yammer alongside Teams. As of now, the app is integrated with a Teams channel. Is it possible to easily integrate the Icebreaker app with Yammer into a Community? Or would this require significant custom development? Thanks!

**Comment by chicago-dev-ui** [comment]
@SrivatsanVasudevan any insight that you can share? Thank you!

**Comment by SrivatsanVasudevan** [comment]
Hi @chicago-dev-ui. I think the best resources to ask this would be the development team of the Icebreaker app, as they would be aware of its overall scope.

From what I am aware about the app is that the way it is built, its scope is entirely Teams centric. The bot is first sideloaded to a team of users, and then it matches users and sends them notifications every week. So all of this has been built keeping the Teams platform in mind, and so I believe it would require significant custom development to integrate this into Yammer.

**Comment by shridharp-ms** [comment]
@chicago-dev-ui This is a teams application. It won't work with Yammer
