### ISSUE TITLE
Deployment via Powershell on OSX

### ISSUE THREAD

**Issue by ecrepeau-sesac** [OfficeDev/microsoft-teams-apps-icebreaker#149]
Script fails to recognize that the Azure CLI is already installed on OS X. Script should be platform agnostic.

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
