### ISSUE TITLE
Error UnresolvableHostName

### ISSUE THREAD

**Issue by LindaSchaar** [OfficeDev/microsoft-teams-apps-icebreaker#150]
Hello,

I have a strange error. Azure says in the runs history form the icebreaker app green check marks. But on almost all icebreaker bots the first run gives an error:

UnresolvableHostName. The provided host name 'icebreaker-...-...-ttdgyml......azurewebsites.net could not be resolved.
I can click and i see: "code": "BadRequest",
    "message": "Http request failed with status code 'NameResolutionFailure' and status message: 'The remote name could not be resolved: 'icebreaker-culture....-ttt.....i5lpq.azureweb.....net''."
 
The dots i placed because i do not want to show everything in this post. If needed i can sent it.

Please help?

**Comment by stevegreenwood** [comment]
+1 on this. I get the same error with the logic code.

**Comment by SubbaReddi** [comment]
You may need to verify allowed characters for app service, logic app, cosmosdb naming etc. Otherwise Please remove special characters from base resource name and deploy. Hope it helps.
