### ISSUE TITLE
which one is version 2 and how to merge?

### ISSUE THREAD

**Issue by markusd1984** [OfficeDev/microsoft-teams-apps-icebreaker#151]
Can somebody please explain which one is version 2? 
Or why there is a v2/main branch and what's the difference to the current main branch?

I'd like to use the current main branch as it contains the deployment powershell scripts, that are unfortunately not in v2/main.

I also would like to make use of the below to make icebreaker more usable for regular intervals

1. [avoiding duplicate/repeat matches](https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/pull/75)  as otherwise can't be used in smaller groups or long term (higher intervals)
2. [handle uneven lists ](https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/issues/72) where the last odd person otherwise would not receive a match 
3. [view available teams and manage active teams ](https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/pull/129#issue-566155022) containted in v2/main,
so users can participate in multiple icebreakers across teams and unsubscribe from individual ones at a later point in time without having to pause all of them.

**Comment by markusd1984** [comment]
Anybody here who knows which branch is version 2 or can confirm that the main master is version 2 and that v2/main is something different?

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
