### ISSUE TITLE
GET calls to /api/messages fail with HTTP error 405 (Method Not Allowed)

### ISSUE THREAD

**Issue by winterminute** [OfficeDev/microsoft-teams-apps-icebreaker#152]
I just got this setup and have seen consistent failures so far.  I modified some of the branding (via params) but otherwise haven't customized the code.  I can hit the base URL directly and get the placeholder "Visit Icebreaker <giturl> to learn more and set one up for your own team!" so I know the site is up and reachable.  Manually triggering the AppLogic does successfully send out pairings.

**Comment by PramodDeokar-ms** [comment]
@winterminute Please share error log details from application Insights.
