### ISSUE TITLE
Question - Does the icebreaker bot work with guests in a tenant?

### ISSUE THREAD

**Issue by JWStarkie** [OfficeDev/microsoft-teams-apps-icebreaker#153]
Hi, 

I'm just wondering if the icebreaker bot would work in the same way with external guests within a Teams team? We have a Teams group set up with internal and external users. I'd really love to know if this works if not, then anything else that may work as an alternative?

Thanks.

**Comment by giannibavetta** [comment]
I too would like to know if guests can be paired. I guess it would not be possible to check availability, however could either party (member or guest) be able to arrange a meeting?

**Comment by davidleeolmstead** [comment]
Remember that the IceBreaker App in Teams is not accessible to Guests, so no, IceBreaker will not operate on external Guest Accounts within your tenant.

**Comment by JWStarkie** [comment]
That's a shame. Thank you for responding 😃
