### ISSUE TITLE
Global Admin accounts locked out

### ISSUE THREAD

**Issue by TashaOD11** [OfficeDev/microsoft-teams-apps-icebreaker#154]
Hello,

I have deployed IceBreaker using this manifest: https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/wiki/Deployment-guide.

I have locked out all GAs, I have tried numerous things ie make myself an owner, via GUI and Powershell.

Is there a specific step / procedure, (perhaps a line to the manifest I missed), to give me owner rights of this enterprise app?

Thank you
Tasha

**Comment by SubbaReddi** [comment]
@TashaOD11 : Global admin account locked out should not happen because of icebreaker app deployment. So, this is not right forum for account lock issue.
