### ISSUE TITLE
HTTP 403 Error

### ISSUE THREAD

**Issue by kbedard8668** [OfficeDev/microsoft-teams-apps-icebreaker#155]
Hi there,

I have the app all set up but the bot doesn't post in Teams or send matches.

I found that I'm getting an HTTP 403 error from the GET request in the Logic App. Has anyone else experienced this?

This customer I'm working with has a 3rd party auth service through Okta. Is it possible that Okta is blocking the get request from going through? If so, does anyone know of a workaround?

Any input is greatly appreciated.

Take Care,
Kim

**Comment by shridharp-ms** [comment]
@kbedard8668 Which graph API is failing in the logic app? Is it using application permission or delegated permission?

**Comment by kbedard8668** [comment]
Thank you for the follow-up. Unfortunately, I never found the root cause. I removed the app and all settings from Teams and Azure and built it fresh. It's now operating as expected.
