### ISSUE TITLE
can we  publish icebreaker bot to teams app store?

### ISSUE THREAD

**Issue by Nandeesh82** [OfficeDev/microsoft-teams-apps-icebreaker#156]
Hi, @jotrick , can we publish the icebreaker bot to teams globally, So whichever the team wants team owner/channel owner can install the icebreaker app in the required teams.

2) also is it possible to set the default meeting time to 15 minutes,

**Comment by shridharp-ms** [comment]
For 2, please refer https://blog.thoughtstuff.co.uk/2019/07/how-to-adjust-the-pairing-schedule-of-the-icebreaker-bot-teams-app-template/

For store apps, you can check out 'Lead.bot'. Icebreaker is an app template that serves as code sample or a quick start for custom LOB application in the organization
