### ISSUE TITLE
unable to receive notifications in Microsoft Teams with icebreaker app

### ISSUE THREAD

**Issue by bneal1987** [OfficeDev/microsoft-teams-apps-icebreaker#160]
Current status:

Icebreaker application was setup and completed in Azure.
Able to load the application to Microsoft Teams Admin center.
Able to see the application in multiple teams when you go to manage teams.
Running the trigger in azure shows successful "Code 200".

Right now, not receiving notifications in the chat section. 

Initally I set this up about 3 weeks ago and tested in a small group and was able to get it to work. As soon as I added to a bigger team, no more notifications. I have completed removed everything and re-setup at least 2-3 times. Looking for any further assistance that you can provide. I can provide screenshots as well. 

Thanks in advance, 
Brandon

**Comment by bneal1987** [comment]
Any update to this post? Looking for a resolution.

**Comment by SubbaReddi** [comment]
Please check application insights to find the root cause of failure.
