### ISSUE TITLE
Run Icebreaaker on demand for testing

### ISSUE THREAD

**Issue by RWilsker** [OfficeDev/microsoft-teams-apps-icebreaker#162]
It's very hard to test Icebreaker when it only runs once a week. Several things would help companies like mine test it:

1. Provide the ability for a Team administrator to trigger an on-demand run of Icebreaker. 
2. Provide a record of what meetups Icebreaker has initiated.

These two features would let us run multiple tests and more easily check on the results.

Thanks.
Roy WIlsker / Medtronic

**Comment by illgitthat** [comment]
@RWilsker you can run it manually by navigating to the logic app in the Azure portal and run the trigger "recurrence" manually.

**Comment by RWilsker** [comment]
Thank you. We finally realized this, but I really appreciate you sending me
this note
