### ISSUE TITLE
Suggestions from our testers

### ISSUE THREAD

**Issue by RWilsker** [OfficeDev/microsoft-teams-apps-icebreaker#163]
- Icebreaker lets the user pause the process, but the user also has to start it up again. One suggestion is to be able to pause it for a fixed time, e.g., two weeks, after which it would start again.

- Icebreaker acts on the entire Team to which it’s been added. It was suggested that it be able to work just with a channel within a team, rather than the entire Team. (So, for example, a Team with many members could create a channel within the Team for people who wanted to meet up with others.)

- It would be nice to be able to add short bios to the meetup request so that people could have a better idea of with whom the bot was matching them. The bio could also include a picture.

- Another idea was to enable badges for people based on how many meetups they had done. (A little competition never hurt anyone! 😊)

- It would be good to get metrics (how many meetups did Icebreaker set up? how many actual meetups resulted?)

**Comment by PramodDeokar-ms** [comment]
For this microsoft-teams-apps-icebreaker repository, we are currently only making changes to fix critical bugs or deployment failures. Please consider forking the repository to implement your improvement and post back here if you're successful.
