### ISSUE TITLE
Bot not working after sideloading into Teams- No confirmation message from app

### ISSUE THREAD

**Issue by Keenesenses** [OfficeDev/microsoft-teams-apps-icebreaker#164]
**hello, I did the recommended configuration in the documentation and everything happened without errors, but when adding the bot in a team it does not generate the meetings. Am I missing a configuration step?**

Guide used: https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/wiki/Deployment-Guide-manual
Video: https://www.youtube.com/watch?v=BkoLT3MEtZg 
 >>>Only deviation is I deployed in East US. I confirmed it has app service for bot<<

 After sideloading into Teams the app shows in channel, but it will not communicate or setup meetings. 
Please help

**Comment by Keenesenses** [comment]
Greetings fellow Icebreaker users / admins,

 I believe I have deployed the resources correctly on the CSP/MPN side tenant, then transferred ownership over to the clients tenant / domain. This resolve most of the errors I was getting with authentication after deploying with OfficeDev's walk-through.
 
 Now I'm getting the following error, but don't know where it is coming from. Could someone please assist?

Experiencing authentication issues
The portal is having issues getting an authentication token. The experience rendered may be degraded.

Additional information from the call to get a token:
Extension: Microsoft_Azure_MonitoringAz
Resource: loganalyticsapi
Details: code: 503, statusText: Service Unavailable, message: ajaxExtended call failed, stack: 

 I also have not sideloaded Icebreaker into Teams yet, as I wanted to know if I could sideload via browser logged in as Global admin for clients tenant?

 Ask any questions I will get whatever logs you will need to assist.

**Comment by Keenesenses** [comment]
So I finally got the Icebreaker bot deployed in Teams, and it is now working. I still need assistance with the following error.

Additional information from the call to get a token:
Extension: Microsoft_Azure_MonitoringAz
Resource: loganalyticsapi
Details: code: 503, statusText: Service Unavailable, message: ajaxExtended call failed, stack:

**Comment by PramodDeokar-ms** [comment]
@Keenesenses Could you please share entire stack trace log from Application Insights.

**Comment by Keenesenses** [comment]
This has already been resolved. Deployed csp side, and had to change
ownership of resources to subdomain for bot to work properly.

Thanks,
Ron

**Comment by kahmed82** [comment]
Hi Ron, can you please share more detail in how you got this working.  I also did the recommended configuration in the documentation and everything happened without errors, but when adding the bot in a team it does not generate the meetings. What could I be missing?

**Comment by SubbaReddi** [comment]
@kahmed82 : When you add bot to team, it shows welcome message in teams channel. But will not generate any meetings. Logic app triggers weekly once and sends matching cards to users. If logic app is not triggering weekly once, check logs.

**Comment by kahmed82** [comment]
@SubbaReddi In trying to troubleshoot I tried to add the app with a different name and this time im getting a "something went wrong" when trying to add the bot to a teams channel. What's the best approach to start form scratch? Thanks.

**Comment by SubbaReddi** [comment]
Click on Manage Team -> Apps -> "Delete the app". So that you can install the app again to same team.

**Comment by Keenesenses** [comment]
If your deploying on the csp side create all resources, secret etc. &
deploy on the csp side. Then log into the client side azure and make this
domain / instance the owner of all the deployed resources, and app. Once
you do this it should move over to the enterprise apps in azure portal.

 At this point try to side load the app in your respective teams channel.

 Hopefully this helps, but if deploying on the csp side I had the issue of
ownership. This might be your issue, and I found it in client side azure
portal to change domain ownership of the resources & app to the sub domain
of our clients primary domain on our side for o365 tenant.

Let me know if this helps, but I recommend to check ownership, & azure app
permissions.

Cheers,
Ron

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!

**Comment by dutystan007** [comment]
I am having similar issues. What was the solution that worked? I setup app alright using shared documentation guide but unable to get the bot to send that initial welcome message when added to a channel

**Comment by Keenesenses** [comment]
I had to deploy the resources on the CSP side, and set it up as an
enterprise app. After I did this I was able to assign users / channels &
they would get a welcome message.

 Works flawlessly now. It's been so long since I deployed so I don't
remember the in's and out's. Any way I can assist let me know. I just know
resources need to be deployed from the CSP tenant
