### ISSUE TITLE
How to keep meet up time for 15 mins by default it is 30 mins

### ISSUE THREAD

**Issue by Nandeesh82** [OfficeDev/microsoft-teams-apps-icebreaker#165]
@shashishailaj, Hi Team, How can we keep the default meetup time for 15 mins, currently it is blocking 30 mins for meetup

**Comment by SubbaReddi** [comment]
@Nandeesh82: Meeting deep link takes 30 minutes by default.
Deep link was generated based on following: https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/blob/main/Source/Icebreaker/Helpers/AdaptiveCards/PairUpNotificationAdaptiveCard.cs#L46

Deep link guidance: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#deep-linking-from-your-tab
