### ISSUE TITLE
Pairing works only for me, none other team members get any notification.

### ISSUE THREAD

**Issue by swapnild2111** [OfficeDev/microsoft-teams-apps-icebreaker#170]
Hello Team,
As per deployment guide, I did all steps. Everything looks fine on Azure side. Created a new Team in Ms Teams & added ice breaker app, then added people.
Now my issue is - I get pairing with other team mates properly as per schedule, however no other team mates get any notification from Icebreaker app regarding their pairing.
What did I miss?

**Comment by SubbaReddi** [comment]
@swapnild2111: Check app permission policies in teams administration whether app allowed for other users or not.
And check application insights to understand failure reason.
