### ISSUE TITLE
Icebreaker Analytics

### ISSUE THREAD

**Issue by gavinbeere1** [OfficeDev/microsoft-teams-apps-icebreaker#171]
Hi there,

Is there anyway to view who has been matched within icebreaker?

We can't seem to find any analytics for this.

Kind regards,
Gavin

**Comment by Nandeesh82** [comment]
@gavinbeere1 , Please check the icebreaker analytics in the same resource groupand the user collection details, there you can filter by pairs notified count, user notified count, etc. It provides details about analytics like how many pairs notified etc.
