### ISSUE TITLE
Changing Bot Message

### ISSUE THREAD

**Issue by aurubis** [OfficeDev/microsoft-teams-apps-icebreaker#173]
Is it possible to change the text from the chat bot:
![image](https://user-images.githubusercontent.com/85112066/120190500-fc21a880-c218-11eb-89c2-5a985f78911c.png)

**Comment by SrivatsanVasudevan** [comment]
Yes, you would have to make the corresponding changes in the Resources.resx file to change the Icebreaker bot text. You can change the text of the labels and buttons of the Icebreaker bot in the file located here: https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/blob/main/Source/Icebreaker/Properties/Resources.resx.

You will have to make these changes in a forked copy of the Icebreaker app, Once you've pushed these changes, then start the manual deployment process of the Icebreaker app, and in step 2, when deploying to Azure, ensure that the field pointing to the Icebreaker Github repo is not pointing to https://github.com/OfficeDev/microsoft-teams-apps-icebreaker and is instead pointing to the forked repo where you have made the required changes.
![githubrepo](https://user-images.githubusercontent.com/29865459/120413949-08d3f880-c30e-11eb-886d-45ab238fe506.png)

**Comment by aurubis** [comment]
Thx for the response.
I will try this out.
