### ISSUE TITLE
Deploying multiple icebreaker bots to the same RG breaks all but the latest one

### ISSUE THREAD

**Issue by taurheim** [OfficeDev/microsoft-teams-apps-icebreaker#177]
The azure logic app fails to get secrets from the key vault - if the permission is manually added it will still fail because the app secret will not be valid (401).

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
