### ISSUE TITLE
Change bots language

### ISSUE THREAD

**Issue by shashkingregory** [OfficeDev/microsoft-teams-apps-icebreaker#178]
Hello! Didnt find any info about the ability to change the language and messages text.
Where should i start&

**Comment by SubbaReddi** [comment]
You can change messages text here: https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/blob/main/Source/Icebreaker/Properties/Resources.resx

**Comment by gavindavies** [comment]
@SubbaReddi does this require rebuilding the solution? We made changes to Resources.resx but this didn't seem to make a change to Resources.Designer.cs after redeploying. Only after making changes in this file did we see the changes in the responses. Thanks!

**Comment by gavindavies** [comment]
When does Resgen.exe get run? During Azure deployment?

**Comment by shashkingregory** [comment]
@SubbaReddi thanks a lot! read all over the documentation but did not find it:)

**Comment by shashkingregory** [comment]
Sorry @gavindavies, i've re-opened issue now

**Comment by SubbaReddi** [comment]
@shashishailaj , @gavindavies : You can change text in Resources.resx, rebuild project and deploy the updated solution to app service.

**Comment by gavindavies** [comment]
@SubbaReddi does the build process happen as part of the deployment to Azure? or do you have to open the solution in VS and build there?

**Comment by SubbaReddi** [comment]
Open solution in VS and build.
