### ISSUE TITLE
Icebreaker Bot Not Working

### ISSUE THREAD

**Issue by majestyuwa** [OfficeDev/microsoft-teams-apps-icebreaker#179]
Hi,

I deployed the icebreaker app to my Teams channel successfully. There seems to be no errors, but the bot does not send any welcome messages or send out matches at the time and day indicated in the parameters json. What is the best way to proceed?

Thanks!

**Comment by SubbaReddi** [comment]
Once you add app to Teams channel, Welcome message must be posted in Teams channel. If it is not, there must be some configuration mistake.
Check app service deployment status and also go through following troubleshooting guide: https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/wiki/Troubleshooting
