### ISSUE TITLE
Deployment fails when the password contains a special character

### ISSUE THREAD

**Issue by mcooley** [OfficeDev/microsoft-teams-apps-icebreaker#180]
The deploy.ps1 script passes a "botAppPassword" value to Azure CLI during deployment. The auto-generated password can contain quote `'`, ampersand `&`, and other special characters. When these special characters are present, there are unexpected errors during deployment.

Some of the symptoms I saw included errors like `(password fragement) is not recognized as an internal or external command,
operable program or batch file.` and `The system cannot find the path specified.`

[Azure CLI in PowerShell generally has issues quoting parameter values, as described here.](https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md) That documentation mentions that one solution might be to format the parameters as JSON and use file input.

**Comment by SubbaReddi** [comment]
@mcooley: I don't see possibility to generate secret key value with special characters quote ', and ampersand &.
It contains majorly following characters only: ., -, _, ~

Based on following [reference](https://github.com/MicrosoftDocs/azure-docs/issues/30467#issuecomment-489918592), some special characters were removed. So, can you confirm if you are able to generate new secret value with quote and ampersand.

**Comment by mcooley** [comment]
I did some more research, and passwords generated with special characters [was a bug in Azure CLI](https://github.com/Azure/azure-cli/issues/13625).

Updating Azure CLI to the latest version fixed the issue.
