### ISSUE TITLE
Message still says 'week' after changing interval to monthly

### ISSUE THREAD

**Issue by gavindavies** [OfficeDev/microsoft-teams-apps-icebreaker#182]
Given that the functionality is there to adjust the interval of messaging, it doesn't make sense to hard code the message intervals that get send to the end users. e.g 'weekly matches' when using a monthly interval.

**Comment by Nandeesh82** [comment]
@gavindavies , SInce text is hardcoded you need make changes in Resource file in icebreaker solution and check the content and change the text.

**Comment by gavindavies** [comment]
@Nandeesh82 Can this be added as a feature? e.g by adding "intervalText" to parameters.json? I have a very large enterprise customer using this solution in the UK who are unsatisfied with having to make these customizations. Would be great if we can add this. Thanks!

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!

**Comment by chartaam** [comment]
I am not the original poster -- but I would like to see this change. It is easy to change the interval, but difficult to change the display text.

**Comment by gsv022** [comment]
Hi @gavindavies ,

Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to close the long pending issues with no resolution/responses. You may always open a new issue if you are still facing the issue. We are closing this request. Thank you!
