### ISSUE TITLE
"Propose Meetup" button tries to schedule a Webinar instead of a Meeting.

### ISSUE THREAD

**Issue by flooidalexfox** [OfficeDev/microsoft-teams-apps-icebreaker#183]
This may have been caused by Webinars being rolled out and changing a key or ID somewhere? Either way I think Icebreaker should link to new meeting requests instead of webinar requests.

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
