### ISSUE TITLE
Paired Match up Report

### ISSUE THREAD

**Issue by kahmed82** [OfficeDev/microsoft-teams-apps-icebreaker#189]
Hi There, 

We would like to pull a report on names for the paired match ups. Is there way to easily find this information?

Many Thanks

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!

**Comment by chartaam** [comment]
I am not the original poster -- but I would also like to have a report for this.

**Comment by v-royavinash** [comment]
@kahmed82  We have added the feature/enhancement request to our backlog items. We will be taking it in our future releases depending upon the priority and bandwidth. For now, we are marking this request closed.
