### ISSUE TITLE
Change name icebreaker

### ISSUE THREAD

**Issue by LindaSchaar** [OfficeDev/microsoft-teams-apps-icebreaker#190]
We had a request about an icebreaker. When you create the bot the bot get the name "IceBreaker"
But we want to change this, but we cannot upload the app in app studio import an existing app fix validation erros
please fix these validation errors and try importing again.
And we want to change the discribtion not this is a cute little bot but something else, somebody can help me?

/developer/privacyURL must match pattern "⌃[Hh][Tt][Tt][Pp][Ss]?://".
/developer/termsOfUserUrl must match pattern "⌃[Hh][Tt][Tt][Pp][Ss]?://".
/developer/websiteUrl must match pattern "⌃[Hh][Tt][Tt][Pp][Ss]?://".

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
