### ISSUE TITLE
Getting "manifest parsing has failed" when uploading to Teams

### ISSUE THREAD

**Issue by csgdeskgithub** [OfficeDev/microsoft-teams-apps-icebreaker#191]
I have attached the Manifest file auto generated for the app template, 
[IceBreaker-manifest.zip](https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/files/7001499/IceBreaker-manifest.zip)

The App studio gave me this,
![app_studio](https://user-images.githubusercontent.com/36534538/129873093-7429e83f-30da-4c31-860c-7ff3b7fc8937.jpg)

I don't understand what 'The file cannot be found' is referring too?

**Comment by zhangjochin** [comment]
Hi, I ran into the same issue. I added en.json file to the zip file and replaced ourline.png with a new file with 32x32 in size. But no luck.

**Comment by csgdeskgithub** [comment]
I had exactly the same issue.
I know this might not be ideal, but have you tried uploading to your tenant’s app catalog?

  1.  You can also upload it to your tenant's app catalog, so that it can be available for everyone in your tenant to install: https://docs.microsoft.com/en-us/microsoftteams/tenant-apps-catalog-teams
This method worked for me.

**Comment by MicrosoftDev365** [comment]
I got the same error when uploading it to app catalog.

**Comment by Aticus23** [comment]
Had some similar issues today, trying to deploy IceBreaker to our tenant. Thanks to the hints here, I was able to resolve the issue:
Within the Manifest Folder, next to the Manifest.zip, there were a bunch of Language Jsons. 
I just bundled the content of the manifest zip with all these language files to a new zip. This got uploaded succesfully. 
Attached a screen of my new manifest zip
![icebreakermanifestzip](https://user-images.githubusercontent.com/31473865/138289464-908af5cc-eae5-4e3b-91c1-e16f30e7bf28.png)
y.

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!

**Comment by taurheim** [comment]
This is definitely still happening, thanks to those here who helped resolve it
