### ISSUE TITLE
thread.skype vs thread.tacv2 in Teams group

### ISSUE THREAD

**Issue by esaito01** [OfficeDev/microsoft-teams-apps-icebreaker#192]
Hello, I have a issue on the Teams group with thread.tacv2 in the link.

I installed a manifest.zip file into two Teams group as custom app. The bot is working in one Teams group but not in another. Based on what I have seen, the difference between them is that the succeeded Teams group has thread.skype in the link and the failed one has thread.tacv2.  

Here is the error message I get every time when the Loggic app starts to connect to the Team group with "thead.tacv2".

Operation returned an invalid status code 'Forbidden'
Problem Id:
Microsoft.Bot.Schema.ErrorResponseException at Icebreaker.Helpers.ConversationHelper+>c_DisplayClass6_0+
＜＜NotifyUserAsync>b_1>d.MoveNext

Any help will be appreciated.

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
