### ISSUE TITLE
Update app password / client secret

### ISSUE THREAD

**Issue by mhf1m1** [OfficeDev/microsoft-teams-apps-icebreaker#193]
Are there documented steps on what to do when the AzureAD Client Secret expires and needs to be renewed? 

I have created a new version of the "MicrosoftAppPassword" secret in the Key Vault and expired the old versions, but my logic app is still failing. In App Insights I see this is the failure which I know is true since the old secret expired. However it does not seem to be taking the new value from KeyVault?

<html>
<body>

Failed to acquire token for client credentials. AADSTS7000215: Invalid client secret is provided.
--

</body>
</html>

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!

**Comment by mhf1m1** [comment]
All set on this, ended up restarting the Azure App Service after updating the keyvault.
