### ISSUE TITLE
Deploy Script prompting for Credentials against all Teams memberships

### ISSUE THREAD

**Issue by ssomu-ms** [OfficeDev/microsoft-teams-apps-icebreaker#194]
I am trying to use the Deploy script to build the package, and am seeing that it is generating an Authentication prompt against all the Azure ADs I am a part of (even other organizations where I was added as a guest for collaboration purposes). I was only trying to target one tenant according to the parameters.json file. 
Should this be happening? I am assuming that it is authenticating and checking my read access against those Azure ADs, but is there a way to restrict it to only check the tenant I am working in, and the one I am trying to target?

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
