### ISSUE TITLE
'Error while reading manifest.json'

### ISSUE THREAD

**Issue by ssomu-ms** [OfficeDev/microsoft-teams-apps-icebreaker#195]
I was able to create the manifest file with the deploy script, but when trying to upload it as a custom app to my team, am getting the message 'Error while reading manifest.json' with no additional information as to why.  How can I gather more information here to troubleshoot?

**Comment by mark3grahams** [comment]
seconded

**Comment by RTIIA** [comment]
Same issue.

**Comment by mark3grahams** [comment]
Look at this.

https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/issues/198

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
