### ISSUE TITLE
V2 Upgrade Instructions

### ISSUE THREAD

**Issue by jeff29922** [OfficeDev/microsoft-teams-apps-icebreaker#196]
I am working with a customer that desires to upgrade Icebreaker to V2.  Is there any documentation detailing the upgrade steps?

**Comment by mw-new-test** [comment]
We at our org also are trying to upgrade Icebreaker to version 2. We added the new manifest package on Teams, but it does not work. On running the Logic app manually, the status shows succeeded within 200ms but does not seem to pair up people in the Team on which Icebreaker is added. Please help.

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!

**Comment by chartaam** [comment]
I am not the original poster -- but I would like to see better documentation for this.

**Comment by gsv022** [comment]
Hi @jeff29922 ,

Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to close the long pending issues with no resolution/responses. You may always open a new issue if you are still facing the issue. We are closing this request. Thank you!
