### ISSUE TITLE
Action required: Update your apps to use Microsoft Graph before 30 June 2022

### ISSUE THREAD

**Issue by RobCRees** [OfficeDev/microsoft-teams-apps-icebreaker#197]
Team-

I received this email from MS regarding updates coming in June 2022.  Is this something that you will be addressing and updating the app that I would then need to re-deploy?

Please advise.

![MS Email](https://user-images.githubusercontent.com/66844167/132404472-b637c26e-0453-453c-a918-b9eead6a4364.jpg)

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
