### ISSUE TITLE
Cannot deploy icebreaker app to teams

### ISSUE THREAD

**Issue by MicrosoftDev365** [OfficeDev/microsoft-teams-apps-icebreaker#198]
Hello,
I have tried both manual deployment and scripted deployment methods provided in the solution. But both methods failed. When I upload the custom app in Teams app, it threw the error "Manifest parsing has failed." The copied error message was "error while reading manifest.json icebreaker". 
I also validated it in App Studio, which indicated an error message of "The file could not be found in the app package". But I don't know which file is missing. Below are the files in my package zip file. Any suggestion on what's going on?
Thank you!
![image](https://user-images.githubusercontent.com/26255679/132584797-cee97aae-b2d4-4f16-a634-b3d7b8bf2f68.png)

**Comment by mark3grahams** [comment]
add the language json files from the manifest into the app.zip

**Comment by MicrosoftDev365** [comment]
Thanks @mark3grahams.  I don't see app.zip anywhere in the icebreaker app solutions. Where can I find it?

**Comment by mark3grahams** [comment]
Sorry that was vague. The manifest folder in the repo has a bunch of language .json files in it. Add those language files to the root of the archive which you created for the app.

**Comment by MicrosoftDev365** [comment]
Thank you @mark3grahams ! This solved the problem!

**Comment by mark3grahams** [comment]
Glad, I could help.
The documentation and the script have not been corrected to account for this.

I guess reasons.

**Comment by thankyou30** [comment]
I am having the same issue. @MicrosoftDev365  can you share me a video of how to do this? I am really new to this. Thank you in advance!

**Comment by LindaSchaar** [comment]
> Sorry that was vague. The manifest folder in the repo has a bunch of language .json files in it. Add those language files to the root of the archive which you created for the app.

Sorry @mark3grahams i do not understand what you mean?

Should i select all language.json files and put them in the icebreaker-manifest.zip file? or should i select all language.json files and zip them and then add in icebreaker-manifest.zip file?

**Comment by LindaSchaar** [comment]
> > Sorry that was vague. The manifest folder in the repo has a bunch of language .json files in it. Add those language files to the root of the archive which you created for the app.
> 
> Sorry @mark3grahams i do not understand what you mean?
> 
> Should i select all language.json files and put them in the icebreaker-manifest.zip file? or should i select all language.json files and zip them and then add in icebreaker-manifest.zip file?

It works!!! @mark3grahams  thanks!!
