### ISSUE TITLE
Incorrectly matching when "optedIn": false

### ISSUE THREAD

**Issue by arnones** [OfficeDev/microsoft-teams-apps-icebreaker#199]
I'm the team owner and I don't have a "pause matches" button. However, my ID does have "optedIn": false.

I don't get messages, but someone got matched with me and messaged me. I'd like to be able to rematch him with someone else and make sure this doesn't happen again.

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
