### ISSUE TITLE
Bot not pairing up users due to Cosmos DB Key changes?

### ISSUE THREAD

**Issue by mw-new-test** [OfficeDev/microsoft-teams-apps-icebreaker#200]
We changed the Cosmos DB Read-Write and Read-only keys on Azure Cosmos DB Account for Icebreaker.
These keys were changed due to vulnerabilities reported by Microsoft
https://msrc-blog.microsoft.com/2021/08/27/update-on-vulnerability-in-the-azure-cosmos-db-jupyter-notebook-feature/

After the keys were changed, On running the Logic app manually, the status shows succeeded within 200ms but does not seem to pair up people in the Team on which Icebreaker is added. 
Could this issue be because of changing the Cosmos DB keys? Please advice.

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
