### ISSUE TITLE
Error with the azuredeploy.json

### ISSUE THREAD

**Issue by Jabberwockz** [OfficeDev/microsoft-teams-apps-icebreaker#201]
Here is my error code, I have this azuredeploy.json in my deployment folder so I am unsure why it us saying there is no such file or directory :( HALP !

Azure AD App: IceBreakerRG registered successfully.
Scan IceBreakerRG source control configuration for conflicts

Deploying app services, Azure function, bot service, and other supporting resources...
az : ERROR: [Errno 2] No such file or directory: 'azuredeploy.json'
At C:\windows\system32\IceBreaker\Deployment\deploy.ps1:359 char:32
+ ... entResult = az deployment group create --resource-group $parameters.r ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: [Errno 2...uredeploy.json':String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
az : ERROR: (DeploymentNotFound) Deployment 'azuredeploy' could not be found.
At C:\windows\system32\IceBreaker\Deployment\deploy.ps1:253 char:5
+     az deployment operation group list --resource-group $parameters.r ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: (Deploym...d not be found.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Collecting deployment logs...
Collecting deployment logs...
Collecting deployment logs...
Collecting deployment logs...
Collecting deployment logs...
Deployment logs generation finished. Please share Deployment\logs.zip file with the app template team to investigate...
Error occurred while deploying Azure resources.
ERROR: ARM template deployment error.
At C:\windows\system32\IceBreaker\Deployment\deploy.ps1:366 char:13
+             Throw $deploymentExceptionMessage
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (ERROR: ARM template deployment error.:String) [], RuntimeException
    + FullyQualifiedErrorId : ERROR: ARM template deployment error.
 
[logs.zip](https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/files/7194856/logs.zip)

**Comment by Jabberwockz** [comment]
Do these issues get resolved?

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!

**Comment by Jabberwockz** [comment]
Yes, it's still an issue!! Don't close this!

**Comment by Jabberwockz** [comment]
Hello, can anyone help with this? :(

**Comment by Porkai-Pandian** [comment]
Hi @Jabberwockz,

Can you please try deploying manually instead of PS script following steps mentioned [here](https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/wiki/Deployment-guide-manual) and let us know if you still face the issue.
