### ISSUE TITLE
Manifest Error 

### ISSUE THREAD

**Issue by zanems** [OfficeDev/microsoft-teams-apps-icebreaker#202]
I have received an error when publishing the manifest to teams. Even with no errors in the app manifest validation tool, the Teams Client will say something went wrong.

Manifest V.1.5

![image](https://user-images.githubusercontent.com/91698552/135529372-c0024f64-a51f-4f8f-ae87-a6c841596b78.png)

![image](https://user-images.githubusercontent.com/91698552/135528288-3163e817-ede5-48c7-9e3a-6b55b278e573.png)

**Comment by SubbaReddi** [comment]
If the bot id is incorrect, then you will see this type of error

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
