### ISSUE TITLE
Script uses Chrome and IE to login into Azure

### ISSUE THREAD

**Issue by mashyoga** [OfficeDev/microsoft-teams-apps-icebreaker#203]
Have tried the automated process. 2 observations.

In step 3 Execute Script, the script does indeed prompt for 2 auths, however, first uses Chrome (works fine) then second time uses IE - which then freezes. On coming out of the execution and re-running the script am stuck in a loop with Chrome to login.

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
