### ISSUE TITLE
How to add a line break in within a Value in the Reources.resx file

### ISSUE THREAD

**Issue by mark3grahams** [OfficeDev/microsoft-teams-apps-icebreaker#204]
Does anyone know what the new line character sequence is for "MatchUpCardContentPart1"?

`I've tried \r, \n, \n\n\, <br /> and &lt;br /&gt;`

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
