### ISSUE TITLE
Button "Propose a meeting" does not work

### ISSUE THREAD

**Issue by shashkingregory** [OfficeDev/microsoft-teams-apps-icebreaker#207]
In a short word: our company works withMicrosoft Exchange 2010 which doesnt support cloud based solutions (such as calendar). So, user cannot create a meeting right after clicking the button.

**Comment by mark3grahams** [comment]
I think Exchange 2010 has been out of support for a year.

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
