### ISSUE TITLE
Icebreaker bot name changed into "Bot User - 93b2e924-acd9-4528-a6ec-844eadb050f6"

### ISSUE THREAD

**Issue by eridakaja** [OfficeDev/microsoft-teams-apps-icebreaker#208]
After implementing "Icebreaker" functionality, we are observing that chat bot name has changed from "Icebreaker" into "Bot User - 93b2e924-acd9-4528-a6ec-844eadb050f6"', any idea why? and how to fix it? Thnx

**Comment by SubbaReddi** [comment]
If the bot channel registration is deleted from azure,you will see this type of error.

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
