### ISSUE TITLE
Source control deployment failed

### ISSUE THREAD

**Issue by rebekahw** [OfficeDev/microsoft-teams-apps-icebreaker#210]
I cloned the source code to our Azure repo, and run the deploy.ps locally. I updated the gitRepoUrl to my devops repo, which caused the issue I think. The Arm template deployment succeeded and the RG created correctly in Azure. 

But it failed when doing source control deployment, and open the log file, which is only contains the []. 

Anyone can give me some thoughts on this issue? Any suggestions for deploy from devops?

**Comment by Porkai-Pandian** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.
