### ISSUE TITLE
How to cxhange App Description (step by step)

### ISSUE THREAD

**Issue by LindaSchaar** [OfficeDev/microsoft-teams-apps-icebreaker#211]
hi All,

I received a request about changing the App Description and then the part "pairs team members up every week" to pairs team members up every two weeks" 

 "appDescription": {
    "Value": "Icebreaker is a cute little bot that randomly pairs team members up every week to help the team build trust and personal connections.",
    "Description": "The app (and bot) description."

Can someone help me with this?

Greetz,
Linda

**Comment by Porkai-Pandian** [comment]
Hi @LindaSchaar

Thank you for raising the query, if you want to change the app description, you can do that while creating the app or update it in manifest.json file, if you want to schedule the app to run every 2 weeks, it can be configured in logic apps that will be created during the app deployment. Please refer to below screenshot and let me know if you've any other query

![image](https://user-images.githubusercontent.com/87537966/142687487-c94263b4-3f8f-46cb-8b5d-1c75a1815337.png)

**Comment by LindaSchaar** [comment]
@Porkai-Pandian thank you for the answer but i want to change the text in app description and description, not the recurrence.

"appDescription": {
"Value": "Icebreaker is a cute little bot that randomly pairs team members up every week to help the team build trust and personal connections.",
"Description": "The app (and bot) description."

Can i change the text while the app is active? and how do i do that?

**Comment by Porkai-Pandian** [comment]
Hi @LindaSchaar,

Unfortunately, you cannot do it after the app is installed, but you can do that in manifest.json file before you install it to Teams.

**Comment by LindaSchaar** [comment]
Hi @Porkai-Pandian 

Again thanks for your answer, this case can be closed. I will try it next week.

Regards,
Linda
