### ISSUE TITLE
Error while reading manifest.json

### ISSUE THREAD

**Issue by LindaSchaar** [OfficeDev/microsoft-teams-apps-icebreaker#212]
![image](https://user-images.githubusercontent.com/49586227/142219207-7bfde0ff-54b7-4dc2-9cff-d11b48181d1f.png)
After installing 10 succesfully bots. Right now the last 2 gives the same error

Error while reading manifest.json

I deploy the bot through powershell.

**Comment by Porkai-Pandian** [comment]
Hi @LindaSchaar,

Thank you for raising the issue, can you please share the manifest.json file which you're trying to upload.

**Comment by LindaSchaar** [comment]
It is solved @Porkai-Pandian i need to select the languegue files and put them in the manifes.zip file and then i can upload the app
