### ISSUE TITLE
Rapport who press pauze in app

### ISSUE THREAD

**Issue by LindaSchaar** [OfficeDev/microsoft-teams-apps-icebreaker#213]
I received a question: is it possible to see who turned the icebreaker bot in a team on "pause"?

**Comment by Porkai-Pandian** [comment]
Hi @LindaSchaar 

Thank you for your query, we'll check it and get back to you on your question

**Comment by Porkai-Pandian** [comment]
Hi @LindaSchaar,

Customer can check their Cosmos DB created for this application, they can see who opted in and who opted out, unfortunately it logs only the Id at the moment, however if you need to know the user name, a graph API call can be made, more details will be available in the below link,

https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http

![image](https://user-images.githubusercontent.com/87537966/143078271-84dfd9a3-142e-4839-b638-5cf923821ce6.png)

**Comment by LindaSchaar** [comment]
Hi @Porkai-Pandian 

Many thanks for your support! I never been there so it is a nice job search. I will try to do it!

Regard,
Linda

**Comment by LindaSchaar** [comment]
@Porkai-Pandian  where can I find the userOptInStatus? in azure cosmos DB?

**Comment by chartaam** [comment]
I have found it difficult to get useful results from just browsing to UsersOptInStatus. It would be great to have a better way to get this information. Also, I have had requests from managers for a way to un-pause users.

**Comment by Porkai-Pandian** [comment]
@LindaSchaar Sorry the delayed response, yes from the Azure Cosmos DB you can find the information, please let us know if you've any other questions, if not we'll close the issue from our end.

**Comment by Porkai-Pandian** [comment]
@chartaam you can get below information (screenshot 1) on the count from Azure App insights, on your other query, admin can un-pause the user by updating the optedIn value to 'True' in the Cosmos DB

<img width="167" alt="image" src="https://user-images.githubusercontent.com/87537966/153090492-07816130-fefe-40c9-9390-ada124ff0a41.png">

![image](https://user-images.githubusercontent.com/87537966/153091102-c433154c-0d25-4d25-be2f-a57a0aa7aa03.png)

**Comment by Porkai-Pandian** [comment]
Please let us know if you've any other queries, if not we'll proceed with closing this issue.
