### ISSUE TITLE
Error reading manifest.json

### ISSUE THREAD

**Issue by IWSitran** [OfficeDev/microsoft-teams-apps-icebreaker#216]
Hello, 
i like th e idea of the app. 
SO i managed to run the registration script succcessfully. I am stuck at trying to install the new app to a team. I tried several ways installing: uploading to the store or adding the app to the organization. Every time i get the errror message "error reading manifest.json" IThe error mesasge does not explain where to find the error. Sideloading apps is allowed in our tenant.
Can you help give me a hint where to look for the error?

Regards
Marcel

**Comment by v-royavinash** [comment]
Hi @IWSitran ,
Thanks for reaching out to us. For validating the manifest file, you can install Team’s app named “**App Studio**”.
Go to the **validation** tab and upload your **manifest package** and validate if there is some error while editing the manifest file.


![image](https://user-images.githubusercontent.com/94480537/144882988-bd37bca5-d34e-45a6-9a52-b27e18664891.png)

**Comment by IWSitran** [comment]
Thanks. That is what i just found out, too. I uploaded the manifest and i was able to find out what th e issue has been. The parameter name is limited to 32 characters. Mine was more than 32 . So some hours wasted but happy it goes on. Thanks for your help.
