### ISSUE TITLE
How to get stats for different teams?

### ISSUE THREAD

**Issue by Nandeesh82** [OfficeDev/microsoft-teams-apps-icebreaker#222]
Hi , I have installed an icebreaker bot in different teams, I want to get the statistics for each team separately, like number of pairs notified, number of users notified, number of users paused @Porkai-Pandian @shashishailaj 
1 icebreaker bot and it is installed in different teams need statistics for each team separately.
from Application insights currently, I am able to get data for 1 teams channel, but how can I get it for different teams.

**Comment by Porkai-Pandian** [comment]
Hi @Nandeesh82,

Thank you for raising the query, as you mentioned the details can be gathered from App Insights, where you can check the number Teams the bot installed as well, however it'll be summary of count and not as per individual team. If you want individual metrics, then you need to go separate deployments for each Teams channel.

<img width="167" alt="image" src="https://user-images.githubusercontent.com/87537966/153088059-b64f7016-6293-4056-9a04-8c4fefaab9ae.png">

**Comment by Porkai-Pandian** [comment]
Hi @Nandeesh82 

Please let us know if you've any other queries, if not we'll proceed with closing this issue.
