### ISSUE TITLE
Bot matches people even if they have both out of office time slots

### ISSUE THREAD

**Issue by chesterb20** [OfficeDev/microsoft-teams-apps-icebreaker#225]
The allocated time between two matches isn't conditioned to be only in an available time slot. For example, a tester got matched with another tester, but it matched them when they are both out of office. Is this something that can be configured in the logic app designer? Thanks!

**Comment by v-royavinash** [comment]
@chesterb20 Thanks for your suggestion. As present we don't check the criteria of matching when they are out of office. We will review the implementation internally and post that will take it as an enhancement.

**Comment by gsv022** [comment]
Hi @chesterb20 ,
We have added this as a enhancement/feature in our backlog items and we will taking it in the future sprints depending on the priority and bandwidth.
