### ISSUE TITLE
Re open Changed bot text in manifest.json file #219

### ISSUE THREAD

**Issue by LindaSchaar** [OfficeDev/microsoft-teams-apps-icebreaker#227]
@Porkai-Pandian unfortunally it does not work. I change it in the resources.resx file each other week. I changed it in the manifest.json file and I changed it in parameters.json file

And it is the same results as my post at the first time
![image](https://user-images.githubusercontent.com/49586227/154052392-d4516adf-1ddd-4f00-b5d1-baf596cb3d0b.png)

Please assist

**Comment by Porkai-Pandian** [comment]
Hi @LindaSchaar,

Thank you for sharing the concern, will validate from our side and get back to you.

**Comment by LindaSchaar** [comment]
@Porkai-Pandian do you al ready have an idea how to fix this?

**Comment by Porkai-Pandian** [comment]
Hi @LindaSchaar, just to confirm, have u changed the highlighted text in Resources.resx file and deployed the bot? Even after modifying the text and deployment, do you see the default text?

![image](https://user-images.githubusercontent.com/87537966/162093742-6e4d99c1-d839-4de2-a792-b9b347c829e4.png)

**Comment by magurrapu** [comment]
@LindaSchaar We have modified the text in the above mentioned place in Properties/Resources.resx file and the text is updating. Please let us if you still need any assistance.

**Comment by LindaSchaar** [comment]
@Porkai-Pandian yes i do so i gave up and told the requestor it is not possible.
Thanks for you help, or do you test this and should it be working now?
Because every time when i test this i need to delete the icebreaker bot en re-install it. The matching start all over again..

**Comment by Porkai-Pandian** [comment]
Yes @LindaSchaar this has been tested and working fine, you need to do the changes and deploy it from the customized branch.

**Comment by Porkai-Pandian** [comment]
Closing the issue as the necessary solution provided, if you still face any issues kindly create a new issue.
