### ISSUE TITLE
Multiple Pairings being sent

### ISSUE THREAD

**Issue by kf-paulbrown** [OfficeDev/microsoft-teams-apps-icebreaker#229]
I recently added IceBreaker to a team and it was running fine on a daily basis for the test group.  I change the run frequency and added 300 "live " users.  The first run was today and the bot sent two pairings to every Team member.  

I can see anywhere obvious to check for multiple accounts or multiple runs.  Could you advise please?

**Comment by Porkai-Pandian** [comment]
Hi @kf-paulbrown 

Thank you for raising the query, you can check the Azure Cosmos DB 'TeamsInstalled' table to see the number of channels where bot is installed. You can also check the Azure app insights on the metrics on the number of channels installed and the number of messages sent etc.

![image](https://user-images.githubusercontent.com/87537966/155246587-9d2ae447-8933-4596-b5ec-8293bc87c30e.png)

**Comment by kf-paulbrown** [comment]
The Cosmos DB shows that the app has been installed in 3 channels (although two of these have been deleted).  I'm having trouble finding the data in the App insights.

**Comment by Porkai-Pandian** [comment]
Hi @kf-paulbrown,

Go to Azure App Insights, look for Event type named 'Custom Event' and look for 'ProcessedPairUps', you should see details like users notified count, installed Teams count etc. 

Refer below screenshot for reference,

![image](https://user-images.githubusercontent.com/87537966/155627918-272a2ea8-5094-4418-bb59-c184f646458d.png)

**Comment by Porkai-Pandian** [comment]
Hi @kf-paulbrown 

Please let us know if you've any other queries, if not we'll proceed with closing this issue.

**Comment by Porkai-Pandian** [comment]
Hi @kf-paulbrown,

Please wait for the next notification scheduled day and check if you're still getting duplicates, if the users are part of more than 1 channel, they might be notified more than once as well.

**Comment by Porkai-Pandian** [comment]
Hi @kf-paulbrown, please let us know if you've any updates on the response provided, if not we'll proceed with closing out the issue.

**Comment by kf-paulbrown** [comment]
Thank you, this issue is resolved.

Kind Regards
Paul Brown
________________________________

Paul BrownBSc. (Hons) (he/him)
Associate, Office 365 Architect
Office 365 | SharePoint | Intranets | Yammer | Teams
______
D:  +44 20 8106 1393
knightfrank.com
S:  +44 20 7629 8171
55 Baker StreetLondon,W1U 8AN,United Kingdom
PA: Paul Brown


This email (including any attachments) is confidential. If it is not addressed to you, please do not read, disclose, copy or forward it on, but notify the sender immediately and delete it. Any copying, disclosure, distribution or other use of this email (and any attachments) by anyone other than the intended recipient is prohibited and may be unlawful. 

This e-mail is sent on behalf of Knight Frank LLP, a limited liability partnership registered in England (registered number OC305934). Our registered office is at 55 Baker Street, London W1U 8AN where you may look at a list of members' names (this can also be found at http://www.knightfrank.co.uk/about-us). If we use the term ‘Partner’ when referring to one of our representatives, that person will either be a Member or an employee of Knight Frank LLP. Knight Frank LLP is authorised and regulated by the Financial Conduct Authority for insurance and mediation activities only. Each entity or practice in the Knight Frank global network is a distinct and separate legal entity. No Knight Frank entity acts as agent for, or has any authority to represent, bind or obligate in any way, any other Knight Frank entity. 

We have tried to ensure this email does not contain any viruses, but please check this before opening any attachments, as we cannot accept any responsibility for damage caused by a virus. Further information concerning our website, information technology and our monitoring, processing and use of personal data can be found at http://www.knightfrank.com/legals. Firms such as Knight Frank LLP and their clients are increasingly being targeted by fraudsters, often requesting funds to be transferred to a different bank account or seeking to obtain confidential information. If you receive a suspicious or unexpected email from us, or purporting to have been sent on our behalf, please do not reply to the email, click on any links, open any attachments, or comply with any instructions contained within it without first speaking (in person or by telephone) with your Knight Frank LLP contact to verify the email. Knight Frank LLP cannot take responsibility for any losses arising from your transfer of funds or disclosure of confidential information.

Except where specifically stated otherwise, any information about price or value contained in this email is provided purely as guidance. It does not constitute a formal valuation and should not be relied upon for any purpose. Unless specifically stated otherwise, any negotiations, intention to treat, offers, acceptances or consideration contained in this email are not intended to create legal obligations or relations and are all subject to contract.
​ [[KFLLP]]
From: Porkai ***@***.***>
Sent: Thursday, April 7, 2022 12:38:00 AM
To: OfficeDev/microsoft-teams-apps-icebreaker ***@***.***>
Cc: Paul Brown ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [OfficeDev/microsoft-teams-apps-icebreaker] Multiple Pairings being sent (Issue #229)


Hi @kf-paulbrown<https://github.com/kf-paulbrown>, please let us know if you've any updates on the response provided, if not we'll proceed with closing out the issue.
