### ISSUE TITLE
PS script is producing the wrong manifest version and incorrect formats

### ISSUE THREAD

**Issue by Yeemonjr** [OfficeDev/microsoft-teams-apps-icebreaker#230]
[Icebreaker (1).zip](https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/files/8157279/Icebreaker.1.zip)

The issue is with the language JSON files

they are all invalid according to the
v1.12

the icons are invalid.
they are smaller than the minimum specified
at least the small one
it should be 32x32

**Comment by Porkai-Pandian** [comment]
Hi @Yeemonjr,

Thank you for sharing your feedback, we'll check the PS script and the deployment using it.

**Comment by Yeemonjr** [comment]
Any updates?

**Comment by magurrapu** [comment]
@Yeemonjr Please update manifest version to V1.5 as the below and it will work fine. 

  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.5/MicrosoftTeams.schema.json",
  "manifestVersion": "1.5",

**Comment by Porkai-Pandian** [comment]
Hi @Yeemonjr, please let us know if you've any updates on the response provided, if not we'll proceed with closing out the issue.
