### ISSUE TITLE
Run history succeeded, but nothing within Teams

### ISSUE THREAD

**Issue by bneal1987** [OfficeDev/microsoft-teams-apps-icebreaker#231]
I noticed over the last 2 monthly runs that the Logic App run successfully, but does not notify within Microsoft Teams. 

Recurrence shows once per month with the HTTP status being 200. If there are specific logs to look at , that would give me a good start to troubleshoot and provide more details when done diagnosing. 

See attached for a couple related items.
[icebreaker issue 3-1-2022.docx](https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/files/8162017/icebreaker.issue.3-1-2022.docx)

**Comment by Porkai-Pandian** [comment]
Hi @bneal1987,

Thank you for raising the query, you can check the Trace in Azure App Insights to check the logs, you can see messages like how many pairs made and notifications sent, refer to below screenshot.

<img width="257" alt="image" src="https://user-images.githubusercontent.com/87537966/156263202-6610e780-d046-4629-a6f9-5099c028860b.png">

**Comment by Porkai-Pandian** [comment]
Hi @bneal1987, please let us know if you've any updates on the response provided, if not we'll proceed with closing out the issue.

**Comment by bneal1987** [comment]
Please close this issue.

Apologies for delay.

Thanks,

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
