### ISSUE TITLE
Always the same match

### ISSUE THREAD

**Issue by Rob1112** [OfficeDev/microsoft-teams-apps-icebreaker#235]
Hello together, 

I use the Icebreaker-App in my Teams-App. We are 14 people in the Icebreaker-Group. Our problem is, that we get always the same two matches. For example: In the first week, person A and B are a match, person C and D and so on. In the second week, there are some other matches, but there are also th same matches. In the third week, there are the same matches as in the first week. 

Is there any random-factor in the code, which we can change for more difference? 

Greetings
Robert

**Comment by Porkai-Pandian** [comment]
Hi @Rob1112, hope we've answered your question, closing this issue, in case you have any follow-up questions, please create new issue
