### ISSUE TITLE
Error while uploading zip file to teams admin portal

### ISSUE THREAD

**Issue by AkashPatel136** [OfficeDev/microsoft-teams-apps-icebreaker#238]
I zipped manifest.json, color.png, outline.png files and when I upload them to the MS teams admin portal it throws the below error message. 
I have changed the bot id and domain URL.

![image](https://user-images.githubusercontent.com/75992078/165179939-04921a4f-f51d-4d77-b036-afef8aebff80.png)

![image](https://user-images.githubusercontent.com/75992078/165180121-06efaac0-9960-4565-81fa-6fea9205feba.png)

**Comment by pezlin** [comment]
I have the same issue. How did you solve it @AkashPatel136-zz?
