### ISSUE TITLE
Deployment guide missing steps for allowing access only from selected networks?

### ISSUE THREAD

**Issue by turbolego** [OfficeDev/microsoft-teams-apps-icebreaker#240]
After setting up the bot, the setting for "Firewall and virtual networks" in Azure is set to:

>Allow access from:
>✔All networks
>❌Selected networks
>All networks, including the internet, can access this Azure Cosmos DB account. [Learn more.](https://docs.microsoft.com/azure/cosmos-db/firewall-support?WT.mc_id=Portal-Microsoft_Azure_DocumentDB)

This seems like a security issue?
Where in the guide should this be changed to a "Selected network" and how?

Thanks!

**Comment by magurrapu** [comment]
@turbolego Thank you for your query. We are looking into it.

**Comment by Porkai-Pandian** [comment]
Hi @turbolego, can you please provide more information like in which service you see this setting?

**Comment by gsv022** [comment]
Hi @turbolego ,
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to close the long pending issues with no resolution/responses. You may always open a new issue if you are still facing the issue. We are closing this request. Thank you!
