### ISSUE TITLE
Azure Cosmos DB TLS certificates

### ISSUE THREAD

**Issue by csgdeskgithub** [OfficeDev/microsoft-teams-apps-icebreaker#241]
Do you know if this app uses Azure Cosmos DB TLS certificates?
[https://devblogs.microsoft.com/cosmosdb/tls-certificates-changes/](url)

**Comment by Porkai-Pandian** [comment]
Hi @csgdeskgithub,

Thank you for raising the query here, as per our understanding, this app doesn't use any certificate for Azure Cosmos DB and don't see any issues with this change mentioned in blog.

**Comment by Porkai-Pandian** [comment]
Hi @csgdeskgithub, I hope we've answered your question, closing this issue, if you still have any questions, please open a new issue.
