### ISSUE TITLE
icebreaker Bot - I'm sorry, but I can't process the incoming message.

### ISSUE THREAD

**Issue by manjunath-bk** [OfficeDev/microsoft-teams-apps-icebreaker#243]
Hi Team,

We recently deployed Icebreaker bot in our tenant, solution deployed without any issues as per the guide.
Issue 1 - Fixed
Manifest package generated for the app template didn't deploy to Teams, when i did some research i found that there was no language specific file in the package, somehow that got fixed and packaged deployed to Teams.

Issue 2 - Open
When Bot gets open for any message it just says "I'm sorry, but I can't process the incoming message. You can take a tour, though, to learn more about my functionality." Attached screenshot for your reference.

Request your assistence on this, as we are planning to deploy this across org next week.

[IcebreakerScreenshots.pdf](https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/files/8860385/IcebreakerScreenshots.pdf)

**Comment by Porkai-Pandian** [comment]
Hi @manjunath-bk,

Thank you for raising the issue, can you please share the manifest zip file uploaded to Teams to validate the issue

**Comment by manjunath-bk** [comment]
HI @Porkai-Pandian 
Thanks for your response, i have attached the manifest file and do the needful.

[IceBreaker.zip](https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/files/8889043/IceBreaker.zip)

**Comment by manjunath-bk** [comment]
Hi @Porkai-Pandian 

Any further update on this request ?

**Comment by Porkai-Pandian** [comment]
Hi @manjunath-bk, your manifest file looks good, please share your email id so that we can troubleshoot the issue over call?

**Comment by manjunath-bk** [comment]
Hi @Porkai-Pandian thanks for your response.
Getting on call really helps, my email id : manjunath.bk@thermofisher.com.
I will be available between 1:00PM to 10:00PM IST tomorrow.
