### ISSUE TITLE
Deployment fails via powershell

### ISSUE THREAD

**Issue by fy-cahill** [OfficeDev/microsoft-teams-apps-icebreaker#244]
I keep getting this error.... 

Updating app secret...
az : WARNING: This command or command group has been migrated to Microsoft Graph API. Please carefully review all breaking changes introduced during this migration: https://docs.microsoft.com/cli/azure/microsoft-graph-migration
At C:\microsoft-teams-apps-icebreaker-main\Deployment\deploy.ps1:232 char:26
+ ... appSecret = az ad app credential reset --id $app.appId --append | Con ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (WARNING: This c...graph-migration:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
ERROR: argument --id: expected one argument
Examples from AI knowledge base:
az ad app credential reset --id 00000000-0000-0000-0000-000000000000
append or overwrite an application's password or certificate credentials (autogenerated)
az ad app credential reset --id 00000000-0000-0000-0000-000000000000 --cert "@~/cert.pem"
Append a certificate to the application with the certificate file.
https://docs.microsoft.com/en-US/cli/azure/ad/app/credential#az_ad_app_credential_reset
Read more about the command in reference docs
Azure AD App: IceBreakerRN registered successfully.
Failed to create or update the app in Azure Active Directory. Exiting...

**Comment by Porkai-Pandian** [comment]
Hi @fy-cahill, thank you for raising the issue, we're looking into it.

**Comment by Porkai-Pandian** [comment]
Hi @fy-cahill, we validated from our side and the deployment works fine, please check if you've given all the necessary fields correctly, you can also try the manual deployment and see if that works for you. Let us know if you still face any problems.

**Comment by Porkai-Pandian** [comment]
Closing the issue since we already provided the response, if you still face any issues, kindly open a new issue
