### ISSUE TITLE
User Reporting/Metrics #139

### ISSUE THREAD

**Issue by LindaSchaar** [OfficeDev/microsoft-teams-apps-icebreaker#246]
I can not add @Nandeesh82?

He answered me with this answer about if it is possible to see how much people pressed pause in a Teams Ice Breaker Bot:
go-to icebreaker analytics and select the user notified count, it will provide details about how many pairs identified. it will not give exactly how many user press pause, but if your team have 100 team members and pair notified count is 40, then assume that 10 users pressed the pause button.

Can you please tell me where is the icebreaker analytics? and how to get the details?
And is there a overview with all bots in one view? or should i select every time a new ice breaker bot?

And the last question were can i sett this up in Azuyre?
https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/wiki/Telemetry

Thanks in advance!

**Comment by Porkai-Pandian** [comment]
Hi @LindaSchaar 

Thank you for posting your query, there are 2 ways where you can identify how many users pressed pause the match, you refer to Azure Cosmos DB table as mentioned in the below image to see how many users have false for optedIn field. 

![image](https://user-images.githubusercontent.com/87537966/174682448-407f08c2-814a-46a4-af16-8837a7f17259.png)

You can also refer to Azure App Insights to get the metrics on how many users notified based on which you can determine the users count who paused the match.

![image](https://user-images.githubusercontent.com/87537966/174682757-3e93181f-3f01-46d6-b280-45f05d8d94ba.png)

**Comment by Porkai-Pandian** [comment]
Hi @LindaSchaar, I hope we've answered your question, closing this issue, if you still have any questions, please open a new issue.
