### ISSUE TITLE
Logic app inquiry

### ISSUE THREAD

**Issue by chesterb20** [OfficeDev/microsoft-teams-apps-icebreaker#250]
Is the logic app setting global? Like if we add the Icebreaker bot to several teams via sideload, do they need to have the same setting?

**Comment by Porkai-Pandian** [comment]
Hi @chesterb20, thank you for raising the query, the logic app is tagged to one instance of the Icebreaker bot, so if you install the icebreaker in multiple teams, the setting will remain same. If you want different settings, then it's recommended to go with another instance of Icebreaker

**Comment by chesterb20** [comment]
> Hi @chesterb20, thank you for raising the query, the logic app is tagged to one instance of the Icebreaker bot, so if you install the icebreaker in multiple teams, the setting will remain same. If you want different settings, then it's recommended to go with another instance of Icebreaker

Thank you. So if I want different settings, how do go about with another instance of Icebreaker? Do you have any documentation on how to do that?

**Comment by Porkai-Pandian** [comment]
@chesterb20 you need to do another deployment following the deployment guide.
