### ISSUE TITLE
Deploy with 2 tenants.

### ISSUE THREAD

**Issue by vcxzzxcv** [OfficeDev/microsoft-teams-apps-icebreaker#251]
Hello.

I have 2 tenants:
First tenant has Azure subscription, but do not have teams licenses.
Second tenant has teams licenses, but has no azure subscription.

Will I be able to deploy on the first tenant and add the bot to a channel belonging to the second tenant?

**Comment by Porkai-Pandian** [comment]
Hi @vcxzzxcv,

Thank you for raising the issue, yes you can do the deployment in one tenant and install the bot in another tenant. Register the bot (step 1 in deployment guide) in the second tenant where you have Teams license, do the deployment in the first tenant (step 2 in the deployment guide) using the Azure subscription. The only change you need to do during deployment is in the 'Tenant Id' field highlighted below, enter the tenant id of the Teams. Please let us know if you've any other questions.

![image](https://user-images.githubusercontent.com/87537966/178654527-fc22414d-60b4-4307-a91b-fb7b564cc974.png)

**Comment by Porkai-Pandian** [comment]
Hi @vcxzzxcv, I hope we've provided the necessary solution, closing this issue, feel free to open new issue in case of any queries.
