### ISSUE TITLE
Unresolvable Host Name

### ISSUE THREAD

**Issue by dtyler3349** [OfficeDev/microsoft-teams-apps-icebreaker#255]
Hi, I'm receiving an UnresolvableHostName failure when the IceBreaker app is trying to run:

Http request failed with status code 'NameResolutionFailure' and status message: 'The remote name could not be resolved: 'icebreaker-.........jiq.azurewebsites.net'

![image](https://user-images.githubusercontent.com/77506935/183715597-c9757fb4-09ba-4fe9-91e1-12b353c7c971.png)

There are no special characters in the name.  Could you please assist?

**Comment by gsv022** [comment]
Hi @dtyler3349 ,
Thank you for your query. We are looking into it.

**Comment by t713005** [comment]
Any update on this? Having this issue

**Comment by gsv022** [comment]
Hi @dtyler3349 ,
Please follow the below steps:-

- Go to azure portal-->Click on resource group-->App Service-->Deployment Center-->**SYNC**
<img width="955" alt="image" src="https://user-images.githubusercontent.com/98143492/185066074-a8c989c0-364a-4d6d-836f-16a4511381fb.png">

- Once the app service is successful. Please proceed with the remaining steps of deployment.  

Keep us posted.

**Comment by t713005** [comment]
I ended up re-uploading the app to Teams and it started working.
