### ISSUE TITLE
ResourceDeploymentFailure - Conflict

### ISSUE THREAD

**Issue by daniel-nov** [OfficeDev/microsoft-teams-apps-icebreaker#256]
Hi, I was trying to deploy the app but I keep getting conflict on "Microsoft.Web/sites/sourcecontrols". 
{
    "status": "Failed",
    "error": {
        "code": "ResourceDeploymentFailure",
        "message": "The resource operation completed with terminal provisioning state 'Failed'."
    }
}

Correlation ID: 85bf525c-c5b7-48a3-bc42-46a0308c6e68. I've tried the new deployment guide but I keep hitting the same error that there's already an open ticket. Can you possibly help me find the root cause? I am co-admin of the resource group.
![Capture1](https://user-images.githubusercontent.com/111354905/184898156-e0baa2c4-b3ba-4966-97e6-8eeba6acb30f.JPG)

**Comment by gsv022** [comment]
Hi @daniel-nov,

Please follow the below steps:-

- Go to azure portal-->Click on resource group-->App Service-->Deployment Center-->**SYNC**
<img width="955" alt="image" src="https://user-images.githubusercontent.com/98143492/185066074-a8c989c0-364a-4d6d-836f-16a4511381fb.png">

- Once the app service is successful. Please proceed with the remaining steps of deployment.  

Keep us posted.

**Comment by daniel-nov** [comment]
Thanks @gsv022 for your reply! I got it to work doing something else and the error is gone. Thanks.
