### ISSUE TITLE
Install fails : write request content-type : not allowed to add 3 passwords

### ISSUE THREAD

**Issue by sentiensx** [OfficeDev/microsoft-teams-apps-icebreaker#258]
Newb here, trying to install my first app from template. have odd errors I havent been able to resolve.  please see content-type header error and how did I put 3 passwords?

Thanks for the help! 

PS C:\temp\icebreaker\deployment> C:\Temp\icebreaker\Deployment\deploy.ps1
Checking if Azure CLI is installed.
Azure CLI is installed.
Checking if the required modules are installed...
Az module is available.
AzureAD module is available.
WriteAscii module is available.
All the modules are available!
Validating all the parameters from parameters.json.
 _                     _                         _                           ____  
(_)  ___   ___        | |__   _ __   ___   __ _ | | __  ___  _ __    __   __|___ \ 
| | / __| / _ \ _____ | '_ \ | '__| / _ \ / _` || |/ / / _ \| '__|   \ \ / /  __) |
| || (__ |  __/|_____|| |_) || |   |  __/| (_| ||   < |  __/| |       \ V /  / __/ 
|_| \___| \___|       |_.__/ |_|    \___| \__,_||_|\_\ \___||_|        \_/  |_____|
Starting deployment...
Login with with your Azure subscription account. Launching Azure sign-in window...

Account                        SubscriptionName                           TenantId                             Environment
-------                        ----------------                           --------                             -----------
person@company.com Azure subscription 1 Microsoft Direct Bill 3e93c60a-2351-4d15-b2aa-0753fd321028 AzureCloud 
az : WARNING: A web browser has been opened at https://login.microsoftonline.com/3e93c60a-2351-4d15-b2aa-0753fd321028/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if 
the web browser fails to open, use device code flow with `az login --use-device-code`.
At C:\Temp\icebreaker\Deployment\deploy.ps1:559 char:13
+     $user = az login --tenant $parameters.subscriptionTenantId.value
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (WARNING: A web ...e-device-code`.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 

Creating Azure AD App: company-IceBreaker...
Updating the existing app...
az : ERROR: Write requests (excluding DELETE) must contain the Content-Type header declaration.
At C:\Temp\icebreaker\Deployment\deploy.ps1:204 char:17
+                 az ad app update --id $app.appId
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: Write re...er declaration.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Waiting for app update to finish...
Azure AD App: company-IceBreaker is updated.
Updating app secret...
az : ERROR: Not allowed to add 3 passwords. You can only add a maximum of 2 passwords.
At C:\Temp\icebreaker\Deployment\deploy.ps1:233 char:26
+ ... appSecret = az ad app credential reset --id $app.appId --append | Con ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: Not allo...of 2 passwords.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Azure AD App: company-IceBreaker registered successfully.
Failed to create or update the app in Azure Active Directory. Exiting...

PS C:\temp\icebreaker\deployment>

**Comment by sentiensx** [comment]
Activity_log.log

[
  {
    "authorization": {
      "action": "Microsoft.Web/serverfarms/write",
      "role": null,
      "scope": "/subscriptions/f3ca53bd-b283-452b-94a7-6bfcd73c9a03/resourcegroups/IceBreakerRG/providers/Microsoft.Web/serverfarms/ascent-icebreaker"
    },
    "caller": "person@company.com",
    "category": {
      "localizedValue": "Administrative",
      "value": "Administrative"
    },
    "channels": "Operation",
    "claims": {
      "aio": "AVQAq/8TAAAAowLgVdHVMOPIfEbDANDqDVl1+31gk9u7QDJYdOidmb4gmzpUsiohiwdQhOHeedzF+N6GjAgijzqUH3jgMyK/FFg62BwYb9Pd1VKgpPayPN8=",
      "appid": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
      "appidacr": "0",
      "aud": "https://management.core.windows.net/",
      "exp": "1659688417",
      "groups": "9b7d0bbc-781a-4b3d-bd2d-9b990a350c75,098cbe76-e1d8-4c59-9022-6ab5bdfca0d7,af9a5c71-8288-4289-a9c2-880f71e4d44e,66e794bb-b1b9-41a6-bbbe-069e9e992fc6,1aaf6413-9b15-43fb-aa41-842141afefc7,e09bdf10-106f-424c-94d6-e87bec0407cf,8040a5c6-0ef2-4a03-96fc-f6e5ff74c40b,84c1b9a3-7db7-426d-a53a-60809ada2389,7abc0801-5dad-4957-8f9b-1cd57fd2369f,f5bcaf95-4712-45f3-af8b-9da42475ea2f",
      "http://schemas.microsoft.com/claims/authnclassreference": "1",
      "http://schemas.microsoft.com/claims/authnmethodsreferences": "pwd,mfa",
      "http://schemas.microsoft.com/identity/claims/objectidentifier": "3339f7e5-64f3-45db-ac50-0f5f7d0fdc95",
      "http://schemas.microsoft.com/identity/claims/scope": "user_impersonation",
      "http://schemas.microsoft.com/identity/claims/tenantid": "3e93c60a-2351-4d15-b2aa-0753fd321028",
      "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname": "person",
      "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name": "person@company.com",
      "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier": "0sNUtrh0Yy6ikRTKFnzMdlvQifJLRmSRdhbbS8spfQ4",
      "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname": "Group",
      "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn": "person@company.com",
      "iat": "1659683973",
      "ipaddr": "73.66.247.100",
      "iss": "https://sts.windows.net/3e93c60a-2351-4d15-b2aa-0753fd321028/",
      "name": "person Group",
      "nbf": "1659683973",
      "onprem_sid": "S-1-5-21-4045000595-1048503424-2928202224-1862",
      "puid": "1003200094658401",
      "rh": "0.ATcACsaTPlEjFU2yqgdT_TIQKEZIf3kAutdPukPawfj2MBM3AF0.",
      "uti": "rkLc3pswt0q1ESTcx_MYAA",
      "ver": "1.0",
      "wids": "69091246-20e8-4a56-aa4d-066075b2a7a8,29232cdf-9323-42fd-ade2-1d097af3e4de,729827e3-9c14-49f7-bb1b-9608f156bbb8,62e90394-69f5-4237-9190-012177145e10,f28a1f50-f6e7-4571-818b-6a12f2af6b6c,fe930be7-5e62-47db-91af-98c3a49a38b1,f023fd81-a637-4b56-95fd-791ac0226033,b79fbf4d-3ef9-4689-8143-76b194e85509",
      "xms_tcdt": "1327535952"
    },
    "correlationId": "a7852913-003b-41c1-83a1-4e984d7158be",
    "description": "",
    "eventDataId": "19a4c6c0-34c7-4048-a297-b5d92b5e9abf",
    "eventName": {
      "localizedValue": "End request",
      "value": "EndRequest"
    },
    "eventTimestamp": "2022-08-05T07:26:19.522744+00:00",
    "httpRequest": null,
    "id": "/subscriptions/f3ca53bd-b283-452b-94a7-6bfcd73c9a03/resourcegroups/IceBreakerRG/providers/Microsoft.Web/serverfarms/ascent-icebreaker/events/19a4c6c0-34c7-4048-a297-b5d92b5e9abf/ticks/637952811795227447",
    "level": "Error",
    "operationId": "e83c6b86-c6c8-49ab-96fe-e2fa32900da1",
    "operationName": {
      "localizedValue": "Update hosting plan",
      "value": "Microsoft.Web/serverfarms/write"
    },
    "properties": {
      "entity": "/subscriptions/f3ca53bd-b283-452b-94a7-6bfcd73c9a03/resourcegroups/IceBreakerRG/providers/Microsoft.Web/serverfarms/ascent-icebreaker",
      "eventCategory": "Administrative",
      "hierarchy": "f3ca53bd-b283-452b-94a7-6bfcd73c9a03",
      "message": "Microsoft.Web/serverfarms/write",
      "statusCode": "Unauthorized",
      "statusMessage": "{\"Code\":\"Unauthorized\",\"Message\":\"This region has quota of 0 instances for your subscription. Try selecting different region or SKU.\",\"Target\":null,\"Details\":[{\"Message\":\"This region has quota of 0 instances for your subscription. Try selecting different region or SKU.\"},{\"Code\":\"Unauthorized\"},{\"ErrorEntity\":{\"ExtendedCode\":\"52039\",\"MessageTemplate\":\"{0}. Try selecting different region or SKU.\",\"Parameters\":[\"This region has quota of 0 instances for your subscription\"],\"Code\":\"Unauthorized\",\"Message\":\"This region has quota of 0 instances for your subscription. Try selecting different region or SKU.\"}}],\"Innererror\":null}"
    },
    "resourceGroup": "IceBreakerRG",
    "resourceGroupName": "IceBreakerRG",
    "resourceId": "/subscriptions/f3ca53bd-b283-452b-94a7-6bfcd73c9a03/resourcegroups/IceBreakerRG/providers/Microsoft.Web/serverfarms/ascent-icebreaker",
    "resourceProviderName": {
      "localizedValue": "Azure Web Sites",
      "value": "Microsoft.Web"
    },
    "resourceType": {
      "localizedValue": "Microsoft.Web/serverfarms",
      "value": "Microsoft.Web/serverfarms"
    },
    "status": {
      "localizedValue": "Failed",
      "value": "Failed"
    },
    "subStatus": {
      "localizedValue": "",
      "value": ""
    },
    "submissionTimestamp": "2022-08-05T07:27:52.146629+00:00",
    "subscriptionId": "f3ca53bd-b283-452b-94a7-6bfcd73c9a03",
    "tenantId": "3e93c60a-2351-4d15-b2aa-0753fd321028"
  },
  {
    "authorization": {
      "action": "Microsoft.Web/serverfarms/write",
      "role": null,
      "scope": "/subscriptions/f3ca53bd-b283-452b-94a7-6bfcd73c9a03/resourcegroups/IceBreakerRG/providers/Microsoft.Web/serverfarms/ascent-icebreaker"
    },
    "caller": "person@company.com",
    "category": {
      "localizedValue": "Administrative",
      "value": "Administrative"
    },
    "channels": "Operation",
    "claims": {
      "aio": "AVQAq/8TAAAAowLgVdHVMOPIfEbDANDqDVl1+31gk9u7QDJYdOidmb4gmzpUsiohiwdQhOHeedzF+N6GjAgijzqUH3jgMyK/FFg62BwYb9Pd1VKgpPayPN8=",
      "appid": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
      "appidacr": "0",
      "aud": "https://management.core.windows.net/",
      "exp": "1659688417",
      "groups": "9b7d0bbc-781a-4b3d-bd2d-9b990a350c75,098cbe76-e1d8-4c59-9022-6ab5bdfca0d7,af9a5c71-8288-4289-a9c2-880f71e4d44e,66e794bb-b1b9-41a6-bbbe-069e9e992fc6,1aaf6413-9b15-43fb-aa41-842141afefc7,e09bdf10-106f-424c-94d6-e87bec0407cf,8040a5c6-0ef2-4a03-96fc-f6e5ff74c40b,84c1b9a3-7db7-426d-a53a-60809ada2389,7abc0801-5dad-4957-8f9b-1cd57fd2369f,f5bcaf95-4712-45f3-af8b-9da42475ea2f",
      "http://schemas.microsoft.com/claims/authnclassreference": "1",
      "http://schemas.microsoft.com/claims/authnmethodsreferences": "pwd,mfa",
      "http://schemas.microsoft.com/identity/claims/objectidentifier": "3339f7e5-64f3-45db-ac50-0f5f7d0fdc95",
      "http://schemas.microsoft.com/identity/claims/scope": "user_impersonation",
      "http://schemas.microsoft.com/identity/claims/tenantid": "3e93c60a-2351-4d15-b2aa-0753fd321028",
      "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname": "person",
      "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name": "person@company.com",
      "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier": "0sNUtrh0Yy6ikRTKFnzMdlvQifJLRmSRdhbbS8spfQ4",
      "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname": "Group",
      "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn": "person@company.com",
      "iat": "1659683973",
      "ipaddr": "73.66.247.100",
      "iss": "https://sts.windows.net/3e93c60a-2351-4d15-b2aa-0753fd321028/",
      "name": "person Group",
      "nbf": "1659683973",
      "onprem_sid": "S-1-5-21-4045000595-1048503424-2928202224-1862",
      "puid": "1003200094658401",
      "rh": "0.ATcACsaTPlEjFU2yqgdT_TIQKEZIf3kAutdPukPawfj2MBM3AF0.",
      "uti": "rkLc3pswt0q1ESTcx_MYAA",
      "ver": "1.0",
      "wids": "69091246-20e8-4a56-aa4d-066075b2a7a8,29232cdf-9323-42fd-ade2-1d097af3e4de,729827e3-9c14-49f7-bb1b-9608f156bbb8,62e90394-69f5-4237-9190-012177145e10,f28a1f50-f6e7-4571-818b-6a12f2af6b6c,fe930be7-5e62-47db-91af-98c3a49a38b1,f023fd81-a637-4b56-95fd-791ac0226033,b79fbf4d-3ef9-4689-8143-76b194e85509",
      "xms_tcdt": "1327535952"
    },
    "correlationId": "a7852913-003b-41c1-83a1-4e984d7158be",
    "description": "",
    "eventDataId": "59701b2d-2d7b-47c4-a835-c6bab7a67f5d",
    "eventName": {
      "localizedValue": "End request",
      "value": "EndRequest"
    },
    "eventTimestamp": "2022-08-05T07:26:19.491448+00:00",
    "httpRequest": {
      "clientIpAddress": "73.66.247.100",
      "clientRequestId": "d596b848-204f-4433-8798-74cc13f662b4",
      "method": "PUT",
      "uri": null
    },
    "id": "/subscriptions/f3ca53bd-b283-452b-94a7-6bfcd73c9a03/resourcegroups/IceBreakerRG/providers/Microsoft.Web/serverfarms/ascent-icebreaker/events/59701b2d-2d7b-47c4-a835-c6bab7a67f5d/ticks/637952811794914486",
    "level": "Error",
    "operationId": "2ee4dd19-60f5-4f5a-98bc-2b7076416ae6",
    "operationName": {
      "localizedValue": "Update hosting plan",
      "value": "Microsoft.Web/serverfarms/write"
    },
    "properties": {
      "entity": "/subscriptions/f3ca53bd-b283-452b-94a7-6bfcd73c9a03/resourcegroups/IceBreakerRG/providers/Microsoft.Web/serverfarms/ascent-icebreaker",
      "eventCategory": "Administrative",
      "hierarchy": "f3ca53bd-b283-452b-94a7-6bfcd73c9a03",
      "message": "Microsoft.Web/serverfarms/write",
      "serviceRequestId": null,
      "statusCode": "Unauthorized",
      "statusMessage": "{\"Code\":\"Unauthorized\",\"Message\":\"This region has quota of 0 instances for your subscription. Try selecting different region or SKU.\",\"Target\":null,\"Details\":[{\"Message\":\"This region has quota of 0 instances for your subscription. Try selecting different region or SKU.\"},{\"Code\":\"Unauthorized\"},{\"ErrorEntity\":{\"ExtendedCode\":\"52039\",\"MessageTemplate\":\"{0}. Try selecting different region or SKU.\",\"Parameters\":[\"This region has quota of 0 instances for your subscription\"],\"Code\":\"Unauthorized\",\"Message\":\"This region has quota of 0 instances for your subscription. Try selecting different region or SKU.\"}}],\"Innererror\":null}"
    },
    "resourceGroup": "IceBreakerRG",
    "resourceGroupName": "IceBreakerRG",
    "resourceId": "/subscriptions/f3ca53bd-b283-452b-94a7-6bfcd73c9a03/resourcegroups/IceBreakerRG/providers/Microsoft.Web/serverfarms/ascent-icebreaker",
    "resourceProviderName": {
      "localizedValue": "Azure Web Sites",
      "value": "Microsoft.Web"
    },
    "resourceType": {
      "localizedValue": "Microsoft.Web/serverfarms",
      "value": "Microsoft.Web/serverfarms"
    },
    "status": {
      "localizedValue": "Failed",
      "value": "Failed"
    },
    "subStatus": {
      "localizedValue": "Unauthorized",
      "value": "Unauthorized"
    },
    "submissionTimestamp": "2022-08-05T07:27:52.146629+00:00",
    "subscriptionId": "f3ca53bd-b283-452b-94a7-6bfcd73c9a03",
    "tenantId": "3e93c60a-2351-4d15-b2aa-0753fd321028"
  }
]

**Comment by sentiensx** [comment]
deployment_operation.log

[
  {
    "additionalInfo": null,
    "code": "Unauthorized",
    "details": [
      {
        "additionalInfo": null,
        "code": null,
        "details": null,
        "message": "This region has quota of 0 instances for your subscription. Try selecting different region or SKU.",
        "target": null
      },
      {
        "additionalInfo": null,
        "code": "Unauthorized",
        "details": null,
        "message": null,
        "target": null
      },
      {
        "additionalInfo": null,
        "code": null,
        "details": null,
        "message": null,
        "target": null
      }
    ],
    "message": "This region has quota of 0 instances for your subscription. Try selecting different region or SKU.",
    "target": null
  },
  {
    "additionalInfo": null,
    "code": "ServiceUnavailable",
    "details": null,
    "message": "Database account creation failed. Operation Id: f2ccafaa-26a0-41a0-b777-cebb9f91a121, Error : Message: {\"code\":\"ServiceUnavailable\",\"message\":\"Sorry, we are currently experiencing high demand in West US 2 region, and cannot fulfill your request at this time. To request region access for your subscription, please follow this link https://aka.ms/cosmosdbquota for more details on how to create a region access request.\\r\\nActivityId: 428029be-2921-422b-a4f9-b41a49fbbfbd, Microsoft.Azure.Documents.Common/2.14.0\"}, Request URI: /serviceReservation, RequestStats: , SDK: Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0",
    "target": null
  }
]

**Comment by v-royavinash** [comment]
@sentiensx ,
 
The first logs shared is related to the PowerShell deployment. PS deployment is dependent on the CLI version that is used. We would suggest to unblock your self, please proceed with the Manual deployment.

Also related to the error _"This region has quota of 0 instances for your subscription."_, What is the region you are using for deployment? Can you please select a different region and try or else please check the subscription quota for the specific region.
