### ISSUE TITLE
Suggestions for improvement of the german translation

### ISSUE THREAD

**Issue by ttran799** [OfficeDev/microsoft-teams-apps-icebreaker#259]
Hi,

could you change the german translation in the "Resources.de.resx" file to the following content:

[https://github.com/ttran799/microsoft-teams-apps-icebreaker/blob/main/Source/Icebreaker/Properties/Resources.de.resx](url)

Kind regards

**Comment by v-royavinash** [comment]
Hi @ttran799 ,

Thanks for suggestion. We will review the suggested changes and update it accordingly.

**Comment by gsv022** [comment]
Hi @v-royavinash,
We have taken your inputs and document will be updated accordingly.

**Comment by ttran799** [comment]
HI @v-royavinash me again, I'm still not seeing the changes regarding the german translation. When can we expect these @gsv022 ?

**Comment by v-royavinash** [comment]
@ttran799  We have pushed the German translation file to the GitHub repo.
