### ISSUE TITLE
DeploymentFailed - Conflict

### ISSUE THREAD

**Issue by markp022** [OfficeDev/microsoft-teams-apps-icebreaker#260]
Hi, we are trying to redeploy the app to resolve some that occurred during a previous installation.

We are following https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/wiki/Deployment-Guide-manual for the installation.

It looks like there is something remaining from a previous installation, that is now blocking the new installation.
How can we find out what it is, and delete it?

The error we're getting is:
Your deployment failed
Resource: ice-breaker-.../web (Type=Microsoft.Web/sites/sourcecontrols, Status=Conflict)
`
    "error": {
      "code": "DeploymentFailed",
      "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
      "details": [
        {
          "code": "Conflict",
          "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\"\r\n  }\r\n}"
        }
      ]
    },
`

The cleanup we did:
- Deleted the icebreaker Resource Group in Azure
- Purged the KeyVault using the "Remove-AzKeyVault -InRemovedState -Force -VaultName ..." command
- Deleted the Permission policy in the Teams admin center
- Deleted the App in the Teams admin center
- Deleted the App registration in the Azure AD console
- Permanently deleted the App registration in the Azure AD console

My account has the global admin role, and the co-owner role on the subscription.
We did take a look at this issue: https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/issues/256 There are a few differences:
- We have already removed the resource group that contained the Icebreaker app.
- Our other resource groups don't have an option "App Service"
- When we go to "App Services" in the Azure portal, we get the message "No app services to display".

**Comment by gsv022** [comment]
Hi @markp022 ,
Thanks for raising the issue. We will look  into this and get back to you soon.

**Comment by gsv022** [comment]
Hi @markp022 ,
Could you please re-sync the app service(microsoft.web/sites) again.

Thank you

**Comment by markp022** [comment]
Thank you for your help. The Sync option was not available, because the App Service was not deployed due to the deployment failure.

I started a new deployment at a quiet time in our Azure region, and this time it worked without an error. The other thing I did different was explicitly set the Tenant Id in the custom template form.

Hopefully this will help someone else in the future:
 - Deploy at a quiet time in your Azure region
 - Enter the Tenant Id explicitly in the custom template form
 - Don't change the Paring Time Zone field (you can change the Pairing Hour)
