### ISSUE TITLE
Icebreaker has stopped working!

### ISSUE THREAD

**Issue by paulmitchell507** [OfficeDev/microsoft-teams-apps-icebreaker#263]
The logic app reports that

  "message": "An error has occurred.",
  "exceptionMessage": "Failed to acquire token for client credentials.",
  
and that the secret keys for the app expired. 
I created new keys (https://aka.ms/NewClientSecret), but I still see a similar error.  Do I need to add the new secret key to any other configuration file?  I don't remember using any keys in the .json file**

**Comment by gsv022** [comment]
Hi @paulmitchell507 ,
Thanks for logging the issue and will get back to you with proper response soon.

**Comment by frank-brandt** [comment]
@paulmitchell507 Sounds like you have the same problem that I had. Check my steps to resolve the problem in https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/issues/264

**Comment by gsv022** [comment]
Hi @paulmitchell507 ,

- It seems that new secret has been created. To confirm whether it has been updated or not. Go to keyvaults -->Secrets-->if don't have permission to view-->Go to Access policies-->Select checkboxes as shown below.-->Add you Id under principal tab-->Create-->Go to Secret whether the new secret has been applied or not.

<img width="899" alt="image" src="https://user-images.githubusercontent.com/98143492/187967231-a8559284-eb80-45d4-8779-1617c1f171d9.png">

![image](https://user-images.githubusercontent.com/98143492/187965528-b1edb93a-2aac-4d0b-b3b1-a6c20be9017c.png)

![image](https://user-images.githubusercontent.com/98143492/187965682-1b48d68b-f293-478e-a052-6c19e12a617b.png)

- To test open the logic app and click run. 


Hope it helps

**Comment by paulmitchell507** [comment]
Thank you for the detailed steps.
I updated the secret as suggested

***@***.***

Now I see a different error message,
exceptionMessage": "AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app 'a025c30b-d675-4166-b791-f5d90475fff7'.\r\nTrace ID: 34b6625a-e1ae-45a8-bfd3-4ee861da8900\r\nCorrelation ID: 78fa83b4-d08b-4184-bc46-4d79d1b959c1\r\nTimestamp: 2022-09-02 09:42:07Z",

Do you think I should generate another new secret and try again?

Full output below.

{
  "message": "An error has occurred.",
  "exceptionMessage": "Failed to acquire token for client credentials.",
  "exceptionType": "System.AggregateException",
  "stackTrace": "   at Microsoft.Bot.Connector.Authentication.Retry.<Run>d__0`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Connector.Authentication.AdalAuthenticator.<GetTokenAsync>d__15.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Connector.Authentication.AdalAuthenticator.<Microsoft-Bot-Connector-Authentication-IAuthenticator-GetTokenAsync>d__16.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Connector.Authentication.AppCredentials.<GetTokenAsync>d__34.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Icebreaker.Controllers.ProcessNowController.<GetAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()",
  "innerException": {
    "message": "An error has occurred.",
    "exceptionMessage": "AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app 'a025c30b-d675-4166-b791-f5d90475fff7'.\r\nTrace ID: 34b6625a-e1ae-45a8-bfd3-4ee861da8900\r\nCorrelation ID: 78fa83b4-d08b-4184-bc46-4d79d1b959c1\r\nTimestamp: 2022-09-02 09:42:07Z",
    "exceptionType": "Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException",
    "stackTrace": "   at Microsoft.Identity.Core.OAuth2.OAuthClient.<GetResponseAsync>d__18`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Identity.Core.OAuth2.OAuthClient.<GetResponseAsync>d__17`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<SendHttpMessageAsync>d__75.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<SendTokenRequestAsync>d__72.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<CheckAndAcquireTokenUsingBrokerAsync>d__62.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<RunAsync>d__60.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenForClientCommonAsync>d__37.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__64.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Connector.Authentication.AdalAuthenticator.<AcquireTokenAsync>d__23.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Connector.Authentication.Retry.<Run>d__0`1.MoveNext()",
    "innerException": {
      "message": "An error has occurred.",
      "exceptionMessage": "Response status code does not indicate success: 401 (Unauthorized).",
      "exceptionType": "Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException",
      "stackTrace": "   at Microsoft.Identity.Core.OAuth2.OAuthClient.<GetResponseAsync>d__18`1.MoveNext()"
    }
  }
}

**Comment by gsv022** [comment]
Hi @paulmitchell507 ,
It seems that the secret ID has been updated instead of secret value. Could you please update with secret value(highlighted one).
<img width="725" alt="image" src="https://user-images.githubusercontent.com/98143492/188556112-ded0a6dd-3aea-4efb-b024-6a823e2076df.png">

**Comment by csgdeskgithub** [comment]
I re-created a secret value and updated the MicrosoftAppPassword in the keyvault but I still see the same error.  Do you think MS support can help?

**Comment by csgdeskgithub** [comment]
As mentioned, 5 days ago, I re-created the secret value, but the error was still showing, and the app was failing.  The app continued to fail until this morning when it started working.
I don't know what to say but thank you for your help!
