### ISSUE TITLE
Oauth Secret expired

### ISSUE THREAD

**Issue by frank-brandt** [OfficeDev/microsoft-teams-apps-icebreaker#264]
Our OAuth secret expired. What is the easiest way to replace it without loosing the database with all the pairing that already happened?
I can generate a new secret, but even if I grant myself permissions in the KeyVault, i cannot replace the secret in the variable MicrosoftAppPassword. Can we just create a new entry with the name MicrosoftAppPassword and the new secret or is the secret referenced with the ID of the key vault entry somewhere else?

**Comment by gsv022** [comment]
Hi @frank-brandt ,
Thanks for raising the issue and will get back to you with proper response soon.

**Comment by frank-brandt** [comment]
I found the solution. Here are the steps that I took:
1) I created a new secret in the IceBreaker OAuth App in Azure AD
2) I granted myself permissions in the IceBreaker key vault to edit secrets
3) I added a new version with the new client secret for secret MicrosoftAppPassword.
4) I removed my permissions in key vault.
5) To test open the logic app and click run or choose adapt the schedule

**Comment by frank-brandt** [comment]
Sure

**Comment by annatindall** [comment]
FYI, I followed @frank-brandt 's solution (thank you!), and additionally had to restart the app service before it would pick up the new secret version as suggested [here](https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/issues/193)
