### ISSUE TITLE
This card action is disabled because you've blocked

### ISSUE THREAD

**Issue by AronPGGM** [OfficeDev/microsoft-teams-apps-icebreaker#269]
The following error message comes up when trying to resume or pause matches:
"This card action is disabled because you've blocked"

This is not the only issue that we are having. Since a while there are no new matches being made. Icebreaker is added, but it does nothing. Any clue what to do?

**Comment by gsv022** [comment]
Hi @AronPGGM ,
Thanks for raising the query. 
- There is possibility that app service might got failed. If yes, please **sync** the app service.

<img width="956" alt="image" src="https://user-images.githubusercontent.com/98143492/187438975-8be821d8-bc20-41af-a60b-7814c6430468.png">

-  If still facing the issue,  please share the app insight logs.

**Comment by AronPGGM** [comment]
Hi @gsv022, thanks for reaching out. We can not find the screen that you communicated. I checked as Teams admin/Sharepoint admin and a colleague checked as Global Reader.

**Comment by AronPGGM** [comment]
Replying so the case will not be closed.

**Comment by gsv022** [comment]
Hi @AronPGGM ,
Could you please confirm that the deployment was done by you or by some other.
To reach the app service. Go to Azure Portal-->Select the resource group (where the icebreaker resources get created)-->Go to App Service-->Click Deployment Center-->Check for success state in the **logs** section
