### ISSUE TITLE
If failure at app install, no "backfill" to try and remedy 

### ISSUE THREAD

**Issue by jotrick** [OfficeDev/microsoft-teams-apps-icebreaker#31]
Currently, if an error is thrown on the membersAdded event when the bot is added at app installation BEFORE the team is installed in the database, then that team will not get matches. The app never tries to rectify this. To fix, the user must remove and reinstall the app.

Proposed fix: on another system activity, if that team has not been saved, try to correct the situation by storing that team info with an "Unknown installer".

**Comment by PramodDeokar-ms** [comment]
For this microsoft-teams-apps-icebreaker repository, we are currently only making changes to fix critical bugs or deployment failures. Please consider forking the repository to implement your improvement and post back here if you're successful.

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
