### ISSUE TITLE
Issue with App Name prevents Cosmos DB from deploying.

### ISSUE THREAD

**Issue by amannall** [OfficeDev/microsoft-teams-apps-icebreaker#43]
Problems deploying the Cosmos DB component - it doesn't like having a "-" in the app name.  I eventually fixed this by removing the "-" from my app name - but it would be nice if you could do this.

**Comment by aosolis** [comment]
Thanks for the suggestion. We'll change the generated name in the template so that it's always a valid Cosmos DB resource name, regardless of the parameters.

**Comment by chartaam** [comment]
I had trouble with "_"
That must have been after the fix for "-" because when I changed that underscore to a hyphen, it did work.

**Comment by Pramoddeokar** [comment]
Thank you for reporting this, we have implemented a fix and pushed it as part of pull request #47. Closing this issue.

**Comment by PramodDeokar-ms** [comment]
Thank you for reporting this, we have implemented a fix and pushed it as part of pull request #47  . Closing this issue.

**Comment by chartaam** [comment]
Great news! Thanks!
