### ISSUE TITLE
HTTP Error 404.3 - Not Found

### ISSUE THREAD

**Issue by kawalid** [OfficeDev/microsoft-teams-apps-icebreaker#51]
HTTP Error 404.3 - Not Found
The page you are requesting cannot be served because of the extension configuration. If the page is a script, add a handler. If the file should be downloaded, add a MIME map.

Requested URL | https://~1thisismysiteurl:80/Content/fonts/glyphicons-halflings-regular.woff
-- | --
D:\Program Files (x86)\SiteExtensions\Kudu\84.10807.4030\Content\fonts\glyphicons-halflings-regular.woff

**Comment by PramodDeokar-ms** [comment]
Hi @kawalid 
We were not able to repro this issue. Let us know if issue still persists for you.
Please try Sync from Web App Deployment center tab.

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
