### ISSUE TITLE
Intermittent missed pairups

### ISSUE THREAD

**Issue by aosolis** [OfficeDev/microsoft-teams-apps-icebreaker#53]
A race condition in the token refresh while processing the pairups trigger can cause missed pairups.
The log will show "Error pairing up team members", with error Unauthorized (status code 401).

**Comment by Pramoddeokar** [comment]
Thank you for reporting this, we have implemented a fix and pushed it as part of pull request #54 . Closing this issue.

**Comment by PramodDeokar-ms** [comment]
Thank you for reporting this, we have implemented a fix and pushed it as part of pull request #54  . Closing this issue.
