### ISSUE TITLE
Matches only happened once

### ISSUE THREAD

**Issue by yahalawa** [OfficeDev/microsoft-teams-apps-icebreaker#55]
Hi Everyone, We have integrated the Icebreaker bot and deployed it as per instructions with a period of matching of 2 weeks. The first time it matches us well. But then after that no matches went out. I checked the deployment and it still says it is active. So I am trying to figure out why matches are not happening anymore. Does anyone have an idea how i can debug this? Also I was wondering is there a way to change the match interval post deployment?

**Comment by rviljoen** [comment]
You may be experiencing #53, which has been fixed. Are you running the latest commit (a85db5e)? You can see which version of the code is by going to the icebreaker App Service->Deployment Centre. If you are running an older version, you can upgrade by clicking Sync.

**Comment by PramodDeokar-ms** [comment]
Thank you for reporting this, we have implemented a fix and pushed it as part of pull request #54  . Closing this issue.
