### ISSUE TITLE
Consider previous matches

### ISSUE THREAD

**Issue by rviljoen** [OfficeDev/microsoft-teams-apps-icebreaker#56]
Our current icebreaker group is about 50 people, but even with such a large group duplicate / repeat matches are a common occurrence. Would be great if the matching algorithm could consider previous matches to avoid duplicates as far as possible, until most people have met with most others.

**Comment by coderkrishna** [comment]
@rviljoen - This is excellent feedback here, however, I'd definitely put this into the UserVoice and provide the appropriate tags there. I'll mark it as a potential request here

**Comment by rviljoen** [comment]
@coderkrishna92 Thanks! Just to be clear, do you want me to log it in UserVoice or will you?

**Comment by coderkrishna92** [comment]
You can log it in UserVoice, and use the hashtag of TeamsAppTemplates for tracking!

**Comment by ksenialesko** [comment]
Hi! I have deployd the Icebreaker bot for our team, and in the second week - some people had the same matches as the week before. Has there been a solution to this and are you please able to share it?

**Comment by trle1994** [comment]
Hello,

Has there been any workaround this? For my team we're experience the same issue where folks are getting repeated matches. Group size is about 18 people.

**Comment by kcuenco** [comment]
Us too. I have been matched with the same person 3 times in a row :(

**Comment by cocochrane** [comment]
Us too. We have 30 people in our team and have encountered repeat matches. What is the status on adding this capability?

**Comment by lucasdreger** [comment]
Hello, we are having the same problem. Same person matching up to 3 times in sequence. Group has 85 members. Kindly advise.

**Comment by Swathi-Shankarnarayana** [comment]
We are having same problem as well. The Bot has now matched same 2 people 2 times. Is there an ETA on when we can expect a fix to have unique matches?

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!

**Comment by rviljoen** [comment]
@v-royavinash Thanks for the update. This is a feature request and not a bug, still to be implemented. If you only want bugs here then you can close it. If you are tracking new features here as well, then please leave it open. Many thanks!

**Comment by v-royavinash** [comment]
@rviljoen We have added the feature/enhancement request to our backlog items. We will be taking it in our future releases depending upon the priority and bandwidth. For now, we are marking this request closed.
