### ISSUE TITLE
Icebreaker Exchange calendar

### ISSUE THREAD

**Issue by IamKukkurloom** [OfficeDev/microsoft-teams-apps-icebreaker#57]
Hello,

We just added Icebreaker bot to our Teams and it is a very good and unique feature to meet colleagues you see maybe once or twice per month.

However we have had some issues with it. When we try to **"Propose meetup"** it will give an error: **"Unable to connect to your Exchange calendar at the moment."** so here comes my question, should it work with Exchange Cloud only or it should work with On-Premise versions aswell?

All the best,
Kukkurloom.

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
