### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by vreezy** [OfficeDev/microsoft-teams-apps-icebreaker#60]
Hello,

i tested the app on an test tenant and it worked nice. 
I deployed the app now on our Company Tenant and i have problems.
First, The matching works!
But if i press the button to show up the popup for more information, nothing happens.
i looked now in the console and everytime i press the button following error shows up:

angular.min.js:113 TypeError: Cannot read property 'name' of undefined
    at https://statics.teams.cdn.office.net/hashedjs/3.2-app.min-3c4b13ae.js:4:1824105
    at f (https://statics.teams.cdn.office.net/hashedjs/0-angular-jquery.min-6dc736c7.js:127:115)
    at https://statics.teams.cdn.office.net/hashedjs/0-angular-jquery.min-6dc736c7.js:127:345
    at m.$eval (https://statics.teams.cdn.office.net/hashedjs/0-angular-jquery.min-6dc736c7.js:142:180)
    at m.$digest (https://statics.teams.cdn.office.net/hashedjs/0-angular-jquery.min-6dc736c7.js:139:290)
    at m.f.$digest (https://statics.teams.cdn.office.net/hashedjs/3.2-app.min-3c4b13ae.js:4:2893550)
    at https://statics.teams.cdn.office.net/hashedjs/0-angular-jquery.min-6dc736c7.js:142:267
    at e (https://statics.teams.cdn.office.net/hashedjs/0-angular-jquery.min-6dc736c7.js:41:350)
    at https://statics.teams.cdn.office.net/hashedjs/0-angular-jquery.min-6dc736c7.js:44:275 undefined

any ideas?

**Comment by coderkrishna92** [comment]
@vreezy - Is there a way you can attach a GIF of what you are experiencing? If not a GIF maybe a few screenshots?

**Comment by vreezy** [comment]
@coderkrishna92 
sorry for the delay. here are the gifs:
Test Tenant: https://ibb.co/T2yrgvF
Prod Tenant: https://ibb.co/tQR28Ly

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
