### ISSUE TITLE
Error when deploying Icebreaker

### ISSUE THREAD

**Issue by kthurman** [OfficeDev/microsoft-teams-apps-icebreaker#62]
I'm getting this error when trying to deploy icebreaker app.
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"code\": \"BadRequest\",\r\n \"message\": \"Database account icebreaker-storage-ik4e36oz5me72 is not online\\r\\nActivityId: d8d656fb-a5cc-4b07-aced-943029dbd476, Microsoft.Azure.Documents.Common/2.10.0\"\r\n}"}]}

**Comment by ritikchanna** [comment]
Are you using free trial ??? Azure is facing heavy traffic due to the global pandemic, Hence this issue on free subscriptions.

**Comment by molislaegers** [comment]
See #59

**Comment by kthurman** [comment]
We are using a Paid subscription.

**Comment by credence-llc-admin** [comment]
Received the same error message when deploying to a Pay-As-You-Go subscription for (US) East US. Any workarounds?

**Comment by JaggB** [comment]
> 
> 
> Received the same error message when deploying to a Pay-As-You-Go subscription for (US) East US. Any workarounds?

Please try North Europe as it worked for us

**Comment by molislaegers** [comment]
West Europe worked for me this time
