### ISSUE TITLE
Please actually explain how this works!

### ISSUE THREAD

**Issue by JustinScarEMC** [OfficeDev/microsoft-teams-apps-icebreaker#63]
Morning!

I am trying to get this app for my org - But when I download it and go to the Teams Admin Center - It will not upload - Now if i do this through the Teams App - App Studio it tells me im missing the JSON manifest but when looking at the download i can see it in there - I am not a programmer but rather a Admin who's users want this. Any help would be appreciated!

Thanks,

Justin

**Comment by mstam13** [comment]
does your zipfile contain a folder structure? Because the manifest.json and both png's should be in the root of the zipfile, not in a folder.

**Comment by JustinScarEMC** [comment]
@mstam13 - It does contain a folder structure - But when unzipping it the folders are empty and if i just try uploading the Zip file directly into the Teams Admin center - It just fails

**Comment by mstam13** [comment]
@JustinScarEMC the zipfile shouldn't contain a folder structure, just 3 files:
the manifest.json, color.png, and outline.png, see the deployment huide here:

https://github.com/OfficeDev/microsoft-teams-icebreaker-app/wiki/Deployment-guide#step-3-create-the-teams-app-package

**Comment by JustinScarEMC** [comment]
@mstam13 - Okay but how do i get it uploaded into Teams? I have tried those steps you linked too and it never uploads and just errors out

**Comment by JustinScarEMC** [comment]
Afternoon,

So when i download the file from the source page - Go into the Zip file - I see the 3 files linked by @mstam13 - Then i go into Teams - App Studio - No matter what I do it will not let me load it.

So i go into Teams Admin Center - It never uploads and just errors out.

What in gods name am I doing wrong?

**Comment by coderkrishna92** [comment]
So a couple of things: @JustinScarEMC Does your tenant for Teams allow for the uploading of custom applications? When you are working with App Studio and importing a manifest, you would need to select only the zip file to upload into app studio.

**Comment by JustinScarEMC** [comment]
@coderkrishna92 - Yes we allow custom apps (Sorry for slow response was out of the office) - Am I downloading the wrong file? Because when I go into the app stupid and try to upload it - It says 
![IB Error](https://user-images.githubusercontent.com/64023809/82908469-a6dbf880-9f2d-11ea-84ce-d2247eaf18f1.JPG) Let me know if that doesn't load.

**Comment by coderkrishna92** [comment]
Ah okay, so double check the zip package. When you extract the zip package, navigate to the JSON file, and make sure that the file name is manifest.json! That's why you're getting the error you are getting. The JSON file inside your compressed folder is not named `manifest.json`

**Comment by JustinScarEMC** [comment]
@coderkrishna92  - So the file inside the zip file is named manifest.json - the file inside the uncompressed file is named manifest.json. Am i looking at the wrong area in this zip file? 
![Manifest](https://user-images.githubusercontent.com/64023809/83039553-f12fa900-a003-11ea-9069-7031335847f0.JPG)

**Comment by mstam13** [comment]
@JustinScarEMC - did you edit the manifest.json as described in the deployment guide?

https://github.com/OfficeDev/microsoft-teams-icebreaker-app/wiki/Deployment-guide:

Step 3: Create the Teams app package
Open the Manifest\manifest.json file in a text editor.

Change the placeholder fields in the manifest to values appropriate for your organization.

developer.name (What's this?)
developer.websiteUrl
developer.privacyUrl
developer.termsOfUseUrl
Change the “botId” placeholder to your Azure AD application's ID from above. This is the same GUID that you entered in the template under “Bot App ID”.

In the "validDomains" section, replace the placeholder with your App Service's domain. This is your App Service's URL you copied above WITHOUT the "https://" e.g. "icebreaker-XXXXXXXXXXXXX.azurewebsites.net".

**Comment by JustinScarEMC** [comment]
@mstam13 - I have never been able to get that deployment guide done...I do not know if its because I am stupid or just not understanding. 

For example: What am I changing for placeholders?? what do i put here? or anything like that.

**Comment by JustinScarEMC** [comment]
@mstam13 -

What do i need to put for the placeholders? My company url?

**Comment by mstam13** [comment]
@JustinScarEMC if that's appropriate, then yes, perhaps your company has public privay and termsofuse url's, you can use those too.
