### ISSUE TITLE
Please add directions on how to change the pairing intervals to wiki (Pull Request not supported for wiki)

### ISSUE THREAD

**Issue by turbolego** [OfficeDev/microsoft-teams-apps-icebreaker#67]
@tomorgan wrote this article on how to change the pairing intervals for icebreaker:

https://blog.thoughtstuff.co.uk/2019/07/how-to-adjust-the-pairing-schedule-of-the-icebreaker-bot-teams-app-template/

Please add his directions to the deployment guide in the wiki.

In case you need illustration screenshots without @tomorgan's watermark, i have uploaded three screenshots without watermark for where to go in order to change the interval settings on imgur, use freely:

step 1: https://i.imgur.com/6vrKXIv.png

step 2: https://i.imgur.com/6sAL3QI.png

step 3: https://i.imgur.com/54HYA3A.png

![Screenshot_1944](https://user-images.githubusercontent.com/2650749/80960657-942c4300-8e09-11ea-932a-d61b2b50a7ee.png)
![Screenshot_1945](https://user-images.githubusercontent.com/2650749/80960662-968e9d00-8e09-11ea-98af-eb75fecd0dbd.png)
![Screenshot_1946](https://user-images.githubusercontent.com/2650749/80960664-98586080-8e09-11ea-8416-542c605c97c2.png)

**Comment by rashmi-dixit** [comment]
Thank you for the feedback. We will share the feedback to the concerned team.

**Comment by chartaam** [comment]
There are multiple requests for this process in the Issues list -- putting it in the Wiki would help people.

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!

**Comment by chartaam** [comment]
@v-royavinash : has it been added to the wiki?
