### ISSUE TITLE
Development Pipeline

### ISSUE THREAD

**Issue by 0xJeremy** [OfficeDev/microsoft-teams-apps-icebreaker#68]
What's the recommend development pipeline for working on this app (ideally locally)? Is it best to use the bot emulator? Or deploy directly to a Teams instance and link it to a locally running version using ngrok?

Thanks.

**Comment by coderkrishna92** [comment]
@0xJeremy That's a great question! The best way to debug this is the latter part, because of the fact that you have the messageBack functionality as part of the "msteams" node in each JSON template of the adaptive cards.

**Comment by 0xJeremy** [comment]
Thanks @coderkrishna92! Does any specific configuration need to be done either in the App Studio in Teams, or in the manifest of the app when running the app locally and tunneling it with ngrok?

I keep running into errors / issues with the app being unable to get information about the Teams channel it is running in.

**Comment by coderkrishna92** [comment]
With regards to the configuration itself, in App Studio make sure you use the ngrok tunnel URL for the bot messaging endpoint please.

**Comment by 0xJeremy** [comment]
Yes, that's all configured appropriately. The issue is with this line:
```
var teams = await this.dataProvider.GetInstalledTeamsAsync();
```
in IcebreakerBot.cs. It's throwing exceptions saying the URI is incorrect (exact error: `Error making pairups: Invalid URI: The URI is empty.`). This is when I try to trigger the pair-up action manually by curling the endpoint of the bot. I bypassed the key check in ProcessNowController.cs by forcing it to always trigger a pairup regardless of the key provided.

This is a pretty specific issue, but do you have any insights on how to go about fixing it? Thanks again for the help!

(In case it's relevant, while bypassing the key-check I also commented out the line `await this.botCredentials.GetTokenAsync();` in ProcessNowController.cs, which was also giving errors. I suspect it's all related to the same issue, but I'm not certain. Advice?)

**Comment by coderkrishna92** [comment]
Aaah! So what you are missing here is a connectionString to Azure Cosmos DB which is why you are getting the URI is empty message. What the Icebreaker Bot does during the pair-ups is that it goes to the TeamsCollection in Azure Cosmos DB to fetch the Team IDs. If there is no Azure Cosmos DB connection string, how is the bot even supposed to know which team(s) the darn thing is installed to?

**Comment by 0xJeremy** [comment]
Yes! In hindsight that would explain many of the errors...

For fear of asking a silly question (but one I don't know the answer to), how does the connectionString get set? Where can it be found and where should I set it when running the app?

**Comment by coderkrishna92** [comment]
While reviewing my original post, I was anticipating that question would arise, and it's not a silly question to ask either! Great questions @0xJeremy! If you look at my updated reply it should help you move along.

**Comment by janvanveldhuizen** [comment]
I am also looking into how to develop my own customizations. I am missing unit tests. Wouldn't it be better to change the architecture in order to be able to add unit tests for the bot class? Or make a separate class for the matching algorithm that we can test locally with xunit?
