### ISSUE TITLE
Matching 1:1 with odd number of team members? Will one user be exluded?

### ISSUE THREAD

**Issue by ulflunqvist** [OfficeDev/microsoft-teams-apps-icebreaker#72]
1) Is it possible to see if user have paused the bot?
2) If odd team member count, do one user get excluded from a match? Is it possible to see who?

**Comment by janvanveldhuizen** [comment]
Yes, one user will be excluded, and he will not be notified about it.
I want to make a change and pull request to change that behavior

**Comment by rashmi-dixit** [comment]
1. Yes it's possible to see, check the Users table in the Azure Comos DB. Kindly refer https://github.com/OfficeDev/microsoft-teams-icebreaker-app/wiki/Data-stores
for details on data stores.
2. Yes, one user gets excluded. The bot logs a few kinds of custom events to Azure Application Insights. For details visit below link. Use the information provided to calculate key metrics.
https://github.com/OfficeDev/microsoft-teams-icebreaker-app/wiki/Telemetry

**Comment by madshaun1984** [comment]
A simple alternative behaviour to this could be,

If Users = Odd, randomly select 1 user and append them to the end of the User list, making the list even, but subject to one users getting two suggestions.

In ../IcebreakerBot.cs
```
private List<Tuple<ChannelAccount, ChannelAccount>> MakePairs(List<ChannelAccount> users)
        {
            if (users.Count > 1)
            {
                this.telemetryClient.TrackTrace($"Making {users.Count / 2} pairs among {users.Count} users");
            }
            else
            {
                this.telemetryClient.TrackTrace($"Pairs could not be made because there is only 1 user in the team");
            }

            // If an odd number of users, randomly select then append one user to make an even list 
            if (users.Count % 2 != 0)
            {
                var random = new Random().Next(1, users.Count);
                users.Add(users[random]);
            }

            this.Randomize(users);

            var pairs = new List<Tuple<ChannelAccount, ChannelAccount>>();
            for (int i = 0; i < users.Count - 1; i += 2)
            {
                pairs.Add(new Tuple<ChannelAccount, ChannelAccount>(users[i], users[i + 1]));
            }

            return pairs;
        } 
```

**Comment by robwales** [comment]
> A simple alternative behaviour to this could be,
> 
> If Users = Odd, randomly select 1 user and append them to the end of the User list, making the list even, but subject to one users getting two suggestions.
> 
> In ../IcebreakerBot.cs
> 
> ```
> private List<Tuple<ChannelAccount, ChannelAccount>> MakePairs(List<ChannelAccount> users)
>         {
>             if (users.Count > 1)
>             {
>                 this.telemetryClient.TrackTrace($"Making {users.Count / 2} pairs among {users.Count} users");
>             }
>             else
>             {
>                 this.telemetryClient.TrackTrace($"Pairs could not be made because there is only 1 user in the team");
>             }
> 
>             // If an odd number of users, randomly select then append one user to make an even list 
>             if (users.Count % 2 != 0)
>             {
>                 var random = new Random().Next(1, users.Count);
>                 users.Add(users[random]);
>             }
> 
>             this.Randomize(users);
> 
>             var pairs = new List<Tuple<ChannelAccount, ChannelAccount>>();
>             for (int i = 0; i < users.Count - 1; i += 2)
>             {
>                 pairs.Add(new Tuple<ChannelAccount, ChannelAccount>(users[i], users[i + 1]));
>             }
> 
>             return pairs;
>         } 
> ```

Could you let me know where I would access this please?

Thank you

**Comment by madshaun1984** [comment]
Finding and replacing the existing "MakePairs" method should do the trick. Although please check this suggestion has not already been included elsewhere as its been a while since I've had time to look IceBreaket myself (someone may have already added and merged it / an alternative).

**Comment by markusd1984** [comment]
@madshaun1984 oh I see now you must have just accidentally referenced the wrong file initially, instead of IceBrakerBot.cs the code changes you suggested relate to MatchingService.cs which I can now recognise and make sense, cheers. https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/blob/main/Source/Icebreaker/Services/MatchingService.cs#L192 

The additional code to insert that you suggested is:
```
// If an odd number of users, randomly select then append one user to make an even list 
            if (users.Count % 2 != 0)
            {
                var random = new Random().Next(1, users.Count);
                users.Add(users[random]);
            }
```

I had another search for "uneven" / "even" related issues but found nothing, this seems to be the only post dealing with this.
