### ISSUE TITLE
Multiple Bots without redeploying each time

### ISSUE THREAD

**Issue by JaggB** [OfficeDev/microsoft-teams-apps-icebreaker#74]
Is it possible to have two different bots deployed into two different channels both matchmaking at different times instead of deploying twice with two different app registration, web apps, cosmo db etc?

**Comment by Srivatsan0102** [comment]
It is possible to have two bots to different channels or teams using the same resources, however the drawback is that both the bots will be running on the same matchmaking interval, and you won't have control on it. By redeploying onto two teams, you will have full control on each bot's matchmaking interval.

**Comment by JaggB** [comment]
Is it possible to shared certain components such as a single CosmoDB?

**Comment by nalhemyariirexorg** [comment]
Did you ever found a solution to this one, I have a requirement to turn this one for 2 teams but different times (one weekly the other monthly)?

**Comment by JaggB** [comment]
> 
> 
> Did you ever found a solution to this one, I have a requirement to turn this one for 2 teams but different times (one weekly the other monthly)?

Nope, We've just been redeploying it as a new instance which is a shame because the only difference is the times it'll run at

**Comment by nalhemyariirexorg** [comment]
@JaggB thanks, so I created a new resource group, deployed, I'm preparing the manifest and uploading to teams, it keep saying the app exist, i change the short and package name, anything else that you have to do to get the package uploading to teams?

**Comment by JaggB** [comment]
> 
> 
> @JaggB thanks, so I created a new resource group, deployed, I'm preparing the manifest and uploading to teams, it keep saying the app exist, i change the short and package name, anything else that you have to do to get the package uploading to teams?

So we've got a one resource group for all of our Teams Bots, we've been deploying it with prefix for each channel ie. Investments-Icebreaker, HR-Icebreaker, IT-Icebreaker. The Bot App ID, Bot App Password and App Name should all be different, Within the manfest file, the only two values you'd need to change is botId and validDomains.

How are you deploying the bot? I'm manually uploading the bot into each time

**Comment by nalhemyariirexorg** [comment]
@JaggB  Thank you, I created a new resource group, and found out about the botid, now its working, not the best approach but it looks like the developed have no intention to enhance the product
