### ISSUE TITLE
App Registration Account Types

### ISSUE THREAD

**Issue by DarrenJ-EMC** [OfficeDev/microsoft-teams-apps-icebreaker#77]
Why specifically do we need to allow this to be accessed by organizations other than our own? We do not have any other app registrations that allow access from entities outside our organization and we do not allow b2b or b2c over teams.

**Comment by Srivatsan0102** [comment]
Multi tenant configuration is required for bot to work when there is manual app registration i.e. manually create your own app ID (and password).
For more details please refer important section in the below page:-
https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-registration?view=azure-bot-service-3.0#manual-app-registration
