### ISSUE TITLE
Force specific time for meetups?

### ISSUE THREAD

**Issue by RobCRees** [OfficeDev/microsoft-teams-apps-icebreaker#78]
We are curious if it's possible to block off a time each week, say from 10am to 10:30am PST on Mondays that employees keep their schedules clear, then the icebreaker app would automatically match the user and set the meeting vs. the 2 users having  to schedule the meeting.

Is this something others have asked about?

Thanks,

**Comment by Srivatsan0102** [comment]
So how you select the matchmaking interval for the bot is something that you will have to select manually, this can be changed by accessing the logic app in the resource group. You will have the provision to change the time and frequency with which the pairing takes place. Keep in mind that there will only be one matchmaking interval for all the employees, so this cannot be configured differently for different employees.

**Comment by RobCRees** [comment]
Once I edit the logic app in Azure, and hit refresh, do i need to reload the tool or that's it?

I just changed from Monday at 10am to Tuesday at 10am successfully.

Thanks,

**Comment by VanyaDob** [comment]
Is it possible to change the default time for the meeting which is 30 minutes? I do not see this in the Logic app. Thanks!

**Comment by RobCRees** [comment]
@VanyaDob we too want to adjust to 15 minutes, if you figure it out please let me know.

**Comment by chartaam** [comment]
I don't have the skillz to write it in C# or add it into the final bot -- but maybe this will help somebody -- figure out the syntax for the URL, and change line 53 in PairUpNotificationCard.cs (in Source\Icebreaker\Helpers\AdaptiveCards):

var meetingLink = "https://teams.microsoft.com/l/meeting/new?subject=" + Uri.EscapeDataString(meetingTitle) + "&attendees=" + recipientUpn + "&content=" + Uri.EscapeDataString(meetingContent);

If it will accept a parament for meeting duration, you could append it to the end of the link string.

**Comment by Nandeesh82** [comment]
@chartaam  @Srivatsan0102  Does the bot excludes from pairing if there calendar is busy or they set Out of Office? we don't people on leave or out of office to be get paired. Since they are Out Of office they cannot pause all matches.

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!

**Comment by chartaam** [comment]
I am not the original poster -- but I would love to see a fix for this issue.

**Comment by gsv022** [comment]
Hi @RobCRees ,

Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to close the long pending issues with no resolution/responses. You may always open a new issue if you are still facing the issue. We are closing this request. 

Thank you!
