### ISSUE TITLE
Bot not working or responding after deployment

### ISSUE THREAD

**Issue by trle1994** [OfficeDev/microsoft-teams-apps-icebreaker#79]
Hello,

I followed the instructions from the video and deployment guide to a T and I'm not sure why the bot isn't responding or working. To give some context, I'm a financial analyst trying to create this to help foster bonding in my org (due to extended WFH), so I don't have much of a technical background. Not only does it not respond or run in Teams but also not respond or run in Web Chat when I tested it either. When I tested it through Emulator, I received the below transcript:

![image](https://user-images.githubusercontent.com/67040757/84860395-cb565c80-b023-11ea-9141-b655e3bfc05d.png)

Can anyone help me understand what is going on and why it's not working like it should? As you can see below, the app is added but the bot isn't showing any messages or features for me to use it:

![image](https://user-images.githubusercontent.com/67040757/84860487-f8a30a80-b023-11ea-984c-57a3b79dcf00.png)

**Comment by Srivatsan0102** [comment]
Hello,
Could you please send a screenshot of your manifest file that was used to upload the icebreaker bot to teams? This way we can double check if you have the correct values there, such as the correct bot ID and the correct app domain values. Also check if you have set the app registration to accounts in any organization.

**Comment by trle1994** [comment]
> Hello,
> Could you please send a screenshot of your manifest file that was used to upload the icebreaker bot to teams? This way we can double check if you have the correct values there, such as the correct bot ID and the correct app domain values. Also check if you have set the app registration to accounts in any organization.

For sure! Please see below:
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.3/MicrosoftTeams.schema.json",
  "manifestVersion": "1.3",
  "version": "1.0.0",
  "id": "d55d08d9-bacb-4567-942f-afd85d632dcc",
  "packageName": "com.microsoft.teams.icebreaker",
  "developer": {
    "name": "Starbucks",
    "websiteUrl": "https://starbucks.com",
    "privacyUrl": "https://starbucks.com/privacy",
    "termsOfUseUrl": "https://starbucks.com/cfp&a"
  },
  "icons": {
    "color": "color.png",
    "outline": "outline.png"
  },
  "name": {
    "short": "Icebreaker"
  },
  "description": {
    "short": "Icebreaker is a bot that randomly pairs team members up to build team unity.",
    "full": "Icebreaker is a cute little bot that randomly pairs team members up every week to help the team build trust and personal connections."
  },
  "accentColor": "#64A2CC",
  "bots": [
    {
      "botId": "0b5632bd-5906-46da-9886-8836cf534690",
      "scopes": [
        "personal",
        "team"
      ],
      "supportsFiles": false,
      "isNotificationOnly": true
    }
  ],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "icebreaker-5cmtqzkx2m3la.azurewebsites.net"
  ]
}

I checked and it is set to "app registration to accounts in any organization.

Please let me know if you need additional information

**Comment by Srivatsan0102** [comment]
Also just to confirm, make sure that you added the bot only to the team and not to the personal scope in your tenant, as it will automatically send messages to your personal scope during the matching interval.

Check your application insights resource and let me know if you face any error messages there, by accessing application insights -> search -> click here to get started -> select any of the exceptions and custom event details to view any possible errors.

**Comment by Srivatsan0102** [comment]
Can you also expand on the exception that you got and attach a screenshot of that as well? We will get more information about what the issue is that way.

**Comment by trle1994** [comment]
yes of course. Please see below:
![image](https://user-images.githubusercontent.com/67040757/85157612-8f341f00-b210-11ea-9796-e7b5bc1afd36.png)
![image](https://user-images.githubusercontent.com/67040757/85157642-9a874a80-b210-11ea-8b30-e9471446644a.png)

**Comment by Srivatsan0102** [comment]
It seems that the app domain is not receiving any messages, it is not available and so that is why it is throwing a 404 error, saying that the app domain is not available. This could be due to an incorrect or failed deployment. If you have a successful deployment and navigate to the app domain, it will throw a message like this: 
![image1](https://user-images.githubusercontent.com/63128678/85167798-408d8180-b21e-11ea-89b0-8b250f18f5fe.png)

Which means that the endpoint is available for sending messages. So, can you check whether you have any failed deployments by selecting the link next to deployments in your resource group? If that is the case, the next best step would be to redeploy, but to make sure you fill in the correct values in the custom deployment section. 

![image3](https://user-images.githubusercontent.com/63128678/85168076-af6ada80-b21e-11ea-869c-dc638d5e6b2b.png)

Ensure that the bot ID matches the application ID from the app registration, and the password matches the bot secret manually created. One deployed, check on the resources created and you should get a message which says the deployment is successful, which means that the app domain has been successfully created.

![image4](https://user-images.githubusercontent.com/63128678/85168236-e8a34a80-b21e-11ea-9d9e-84042c12add5.png)

**Comment by trle1994** [comment]
> It seems that the app domain is not receiving any messages, it is not available and so that is why it is throwing a 404 error, saying that the app domain is not available. This could be due to an incorrect or failed deployment. If you have a successful deployment and navigate to the app domain, it will throw a message like this:
> ![image1](https://user-images.githubusercontent.com/63128678/85167798-408d8180-b21e-11ea-89b0-8b250f18f5fe.png)
> 
> Which means that the endpoint is available for sending messages. So, can you check whether you have any failed deployments by selecting the link next to deployments in your resource group? If that is the case, the next best step would be to redeploy, but to make sure you fill in the correct values in the custom deployment section.
> 
> ![image3](https://user-images.githubusercontent.com/63128678/85168076-af6ada80-b21e-11ea-869c-dc638d5e6b2b.png)
> 
> Ensure that the bot ID matches the application ID from the app registration, and the password matches the bot secret manually created. One deployed, check on the resources created and you should get a message which says the deployment is successful, which means that the app domain has been successfully created.
> 
> ![image4](https://user-images.githubusercontent.com/63128678/85168236-e8a34a80-b21e-11ea-9d9e-84042c12add5.png)

Thank you! I'll try to redeploy. Do I need to cancel the original deployment somehow?

**Comment by Srivatsan0102** [comment]
So in case of a redeployment, it is recommended that you delete the resources you created in the resource group and start again using the same resource group and also create a new app registration with a new app ID and bot secret.

**Comment by trle1994** [comment]
I redeployed and this time around, it pops up a message for take a tour but nothing else after that. Even going directly to the app there's no chatbox
![image](https://user-images.githubusercontent.com/67040757/86833835-ededfb00-c04e-11ea-8493-33af16e6e51d.png)
![image](https://user-images.githubusercontent.com/67040757/86833869-f5ad9f80-c04e-11ea-916d-5d960a1e6714.png)

I went to application insights and saw the below, Im not sure what they mean:
![image](https://user-images.githubusercontent.com/67040757/86834060-373e4a80-c04f-11ea-8032-d2a2f578da5b.png)

**Comment by trle1994** [comment]
Nevermind! It actually worked when I brought my teammates in and they were able to see the Pause Matches option.

**Comment by kahmed82** [comment]
Hi Everyone - Can someone please advise me how to resolve a similar issue im facing with icebreaker. 
The deployment looks fine in Azure, just not receiving any messages.

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!

**Comment by yomofo2s** [comment]
![image](https://user-images.githubusercontent.com/44329653/152927810-865fbf3e-8707-4de1-9aa1-e8ce21063984.png)

i do not know why my deployent refuses to pair up

can someone help?
