### ISSUE TITLE
Possible to change pairing sizes?

### ISSUE THREAD

**Issue by chrimorgan** [OfficeDev/microsoft-teams-apps-icebreaker#80]
Is it possible to change the bot to group by 3's or 4's, instead of by 2's?

**Comment by Srivatsan0102** [comment]
Hi,
The current version of Icebreaker only supports pairs of 2's as the default value. You would have to make the appropriate code changes to this file https://github.com/OfficeDev/microsoft-teams-icebreaker-app/blob/master/Source/Icebreaker/IcebreakerBot.cs to change the pair sizes.

**Comment by chrimorgan** [comment]
Thanks for the reply! So, essentially, I'd change the 

``          var pairs = new List<Tuple<ChannelAccount, ChannelAccount>>();
            for (int i = 0; i < users.Count - 1; i += 2)`

to "i += 4" if we wanted groups of 4? `Then also add corresponding "var teamsPerson3/4" statements? Am I missing anything else you can think of?

**Comment by RobCRees** [comment]
This would be great, we too would like this feature, can you please advise if you get this working?

**Comment by MaggiMartens** [comment]
@chrimorgan did you find a solution for this?

**Comment by fixxxer77** [comment]
@chrimorgan Any update, if you managed to change pair size?

**Comment by lucasdreger** [comment]
Hello @chrimorgan I am also interested in hearing more about it.

**Comment by PramodDeokar-ms** [comment]
For this microsoft-teams-apps-icebreaker repository, we are currently only making changes to fix critical bugs or deployment failures. Please consider forking the repository to implement your improvement and post back here if you're successful.

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
