### ISSUE TITLE
ICEBREAKER IS NOT WORKING

### ISSUE THREAD

**Issue by charlottefrancois** [OfficeDev/microsoft-teams-apps-icebreaker#81]
Hello,

I installed icebreaker by following the deployment tutorial. I didn't get any errors or issues , however, the user is not the same as the one described in the video. I tested with a guest account and a team member account. I can only see in the team history that icebreaker has been added but I don't get the welcome message , I only see a link to icebreaker.
![image](https://user-images.githubusercontent.com/67419631/85721564-c3687d80-b6f1-11ea-8a25-1814dd7d4089.png)
![Capture2](https://user-images.githubusercontent.com/67419631/85721667-dbd89800-b6f1-11ea-9c56-247ae7e86c93.PNG)

**Comment by Srivatsan0102** [comment]
Hi,

The Icebreaker bot is a team scope bot, so it works by adding it to a team and then adding the members to the team who you want to be matched by the Icebreaker bot. If you're not getting the welcome message in the team, there could be some issues with the deployment of the bot. Can you please share your manifest file you created for uploading the bot to the team?

Also redirect to your app domain in a new tab and see what message you are getting. A working instance of Icebreaker will throw a message like this:
![image](https://user-images.githubusercontent.com/63128678/85759703-06146080-b6c6-11ea-915f-46a58e36acd8.png)

**Comment by charlottefrancois** [comment]
Hello,

Thanks for your reply.
Here is the content of the manifest
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.3/MicrosoftTeams.schema.json",
  "manifestVersion": "1.3",
  "version": "1.0.0",
  "id": "d55d08d9-bacb-4567-942f-afd85d632dcc",
  "packageName": "com.microsoft.teams.icebreaker",
  "developer": {
    "name": "thoughtstuff",
    "websiteUrl": "https://thoughtstuff.co.uk",
    "privacyUrl": "https://thoughtstuff.co.uk/privacy",
    "termsOfUseUrl": "https://thoughtstuff.co.uk/tos"
  },
  "icons": {
    "color": "color.png",
    "outline": "outline.png"
  },
  "name": {
    "short": "Icebreaker"
  },
  "description": {
    "short": "Icebreaker is a bot that randomly pairs team members up to build team unity.",
    "full": "Icebreaker is a cute little bot that randomly pairs team members up every week to help the team build trust and personal connections."
  },
  "accentColor": "#64A2CC",
  "bots": [
    {
      "botId": "5af05baf-1478-4256-9bcd-c80b265e9fcb",
      "scopes": [
        "personal",
        "team"
      ],
      "supportsFiles": false,
      "isNotificationOnly": true
    }
  ],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "icebreaker-qf4x7gnorrl5o.azurewebsites.net"
  ]
}

**Comment by charlottefrancois** [comment]
when I clicked on the link displayed in my team I only see what is showing on the attached screenshot:
![Capture3](https://user-images.githubusercontent.com/67419631/85833804-99b36300-b792-11ea-82fb-be9c0e15eb37.PNG)

The link is working https://icebreaker-qf4x7gnorrl5o.azurewebsites.net/

**Comment by Srivatsan0102** [comment]
In that case, the bot should be working... When you sideload the bot to the team, make sure you sideload it by selecting the ellipsis next to the team name, select manage team, select apps, then in the bottom right corner there should be an option to upload a custom app -> from there select the icebreaker manifest. This will upload the bot to the team and in the general channel you should get a welcome message.

A workaround for this is to select apps in the bottom left corner, and select upload a custom app -> upload for me or my teams, then select the Icebreaker bot. When adding, select the drop down and select add to team, then select the team to which you will add the bot to and you should be getting the welcome message in the general channel.

**Comment by charlottefrancois** [comment]
I did that , exactly as you explained in your previous post but I didn't get any welcome message, just a link "icebreaker" 
![Capture4](https://user-images.githubusercontent.com/67419631/85986857-248f9a00-b9ed-11ea-8702-57fb57cb4e46.PNG)

I also tried with another channel but I have the same issue.

**Comment by trle1994** [comment]
did you ever get this resolved? I have a similar issue as well

**Comment by tsharma90** [comment]
Any luck with this one? I have the exact same issue!

**Comment by jainmilan002** [comment]
I am facing similar issue. Did follow deployment guide but still got the same issue. Logic app run is failing every time.
Below is the error which I am getting while running logic app:
{
    "statusCode": 500,
    "headers": {
        "Pragma": "no-cache",
        "Request-Context": "appId=cid-v1:751b8f65-b618-4a2e-8434-5ccc7d4a2413",
        "Access-Control-Expose-Headers": "Request-Context",
        "Cache-Control": "no-cache",
        "Date": "Mon, 05 Oct 2020 09:09:52 GMT",
        "Set-Cookie": "ARRAffinity=faf4dec0e866a78a704d6f50882bec16fc24fe887063009bbdffd2526cac326f;Path=/;HttpOnly;Domain=icebreaker-jkhi4du7pxw6i.azurewebsites.net",
        "Server": "Microsoft-IIS/10.0",
        "X-AspNet-Version": "4.0.30319",
        "X-Powered-By": "ASP.NET",
        "Content-Length": "2817",
        "Content-Type": "application/json; charset=utf-8",
        "Expires": "-1"
    },
    "body": {
        "message": "An error has occurred.",
        "exceptionMessage": "Unauthorized",
        "exceptionType": "Microsoft.Bot.Connector.MicrosoftAppCredentials+OAuthException",
        "stackTrace": "   at Microsoft.Bot.Connector.MicrosoftAppCredentials.<RefreshTokenAsync>d__34.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Bot.Connector.MicrosoftAppCredentials.<GetTokenAsync>d__27.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Icebreaker.Controllers.ProcessNowController.<Get>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()",
        "innerException": {
            "message": "An error has occurred.",
            "exceptionMessage": "Response status code does not indicate success: 401 (Unauthorized).",
            "exceptionType": "System.Net.Http.HttpRequestException",
            "stackTrace": "   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()\r\n   at Microsoft.Bot.Connector.MicrosoftAppCredentials.<RefreshTokenAsync>d__34.MoveNext()"
        }
    }
}

**Comment by 1BJK903** [comment]
Any update on this?

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
