### ISSUE TITLE
[Feature Request] Add a way to limit teams the bot can be added to.

### ISSUE THREAD

**Issue by madshaun1984** [OfficeDev/microsoft-teams-apps-icebreaker#82]
For testing / governance purposes, it may be beneficial to have a way to limit the teams the bot can be added too.

Something like having a comma delimited "Test Team" config setting that lists the teams the bot is allowed to be installed on, but causes a rejection message during install attempts from all other teams.

**Comment by Srivatsan0102** [comment]
Thank you for your suggestion! We will inform the corresponding team about this feature request.

**Comment by PramodDeokar-ms** [comment]
For this microsoft-teams-apps-icebreaker repository, we are currently only making changes to fix critical bugs or deployment failures. Please consider forking the repository to implement your improvement and post back here if you're successful.

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
