### ISSUE TITLE
Feature Request- Companywide scheduled blackout for icebreaker?

### ISSUE THREAD

**Issue by RobCRees** [OfficeDev/microsoft-teams-apps-icebreaker#83]
We are trying to understand if it would be possible to dedicate a time (10am to 10:30am) for all employees in the company to not have any external meetings.

The goal would be that everyone calendar is blocked during this time, but that the icebreaker app that pairs you up at 10am would automatically schedule the meeting for your meetup at 10am.

this way it helps increase adoption as your calendar is not booked.

any other users asking for something like this or see benefit?

**Comment by PramodDeokar-ms** [comment]
For this microsoft-teams-apps-icebreaker repository, we are currently only making changes to fix critical bugs or deployment failures. Please consider forking the repository to implement your improvement and post back here if you're successful.

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
