### ISSUE TITLE
Change the default time for a meetup

### ISSUE THREAD

**Issue by VanyaDob** [OfficeDev/microsoft-teams-apps-icebreaker#86]
We want to change the default time for the meetup which is now 30 minutes. We would like to make shorter meetups (15 min). Is there a way to do it without changing the code but somewhere from Azure? Thanks in advance!

**Comment by RobCRees** [comment]
We also would like to adjust the default from 30 minutes to 15 minutes, within the Logic App I am able to adjust the meeting date and time (hour of the day) but not adjust the MEETING TIME.

Please advise how we can do that.

**Comment by chartaam** [comment]
I don't have the skillz to write it in C# or add it into the final bot -- but maybe this will help somebody -- figure out the syntax for the URL, and change line 53 in PairUpNotificationCard.cs (in Source\Icebreaker\Helpers\AdaptiveCards):

var meetingLink = "https://teams.microsoft.com/l/meeting/new?subject=" + Uri.EscapeDataString(meetingTitle) + "&attendees=" + recipientUpn + "&content=" + Uri.EscapeDataString(meetingContent);

If it will accept a parament for meeting duration, you could append it to the end of the link string.

**Comment by PramodDeokar-ms** [comment]
Meeting deep link takes 30 minutes by default.
Deep link was generated based on following: [https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/blob/main/Source/Icebreaker/Helpers/AdaptiveCards/PairUpNotificationAdaptiveCard.cs#L46](url)

Deep link guidance: [https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#deep-linking-from-your-tab](url)

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
