### ISSUE TITLE
Changing Message

### ISSUE THREAD

**Issue by JoeSMGraham** [OfficeDev/microsoft-teams-apps-icebreaker#87]
Is it possible to change the wording of the IceBreaker messages that are triggered to teams?

**Comment by JaggB** [comment]
+1 I've also had a request come through from the users asking it to be changed. ie. Message says that it runs every week when we've got it running every two weeks.

**Comment by JoeSMGraham** [comment]
We have done the same, every 2 weeks.  Be good to personalise the message that is sent.

**Comment by gdherbert** [comment]
You can fork this repo and make the language changes in the Resources.resx section. You will need to disconnect the existing app and reconnect it to your form to push those changes in.

**Comment by JoeSMGraham** [comment]
Hi gdherbert,

Can you provide instructions to achieve this?

Thanks

Joe

**Comment by JaggB** [comment]
HI @gdherbert 

How do you do that without completely removing the bot as it's currently in prob?

Thanks
Jag

**Comment by gdherbert** [comment]
You can do this without removing the bot. 
1. Fork this repo into your own account and make a note of the URL. 
2. In Azure go to the App Service
3. Go to the Deployment Center and click Disconnnect.
4. Then you can add a new deployment and point it at the url you have above. 
https://docs.microsoft.com/en-us/azure/app-service/deploy-continuous-deployment#:~:text=In%20the%20Azure%20portal%2C%20search%20for%20App%20Services%2C%20and%20then,Center%20page%2C%20and%20select%20Continue.
- I chose to do this through Kudu as the previous one was. 
5. Make changes in your repo to the text, commit and push to GitHub (or edit directly on GitHub and commit)
6. Back in Azure you should see a deployment automatically updating and hopefully a success message.  You can also click Sync.

**Comment by JaggB** [comment]
@gdherbert Thank you, will try this out. Much appreciated
