### ISSUE TITLE
Updated Icebreaker app? (called something different)?

### ISSUE THREAD

**Issue by RobCRees** [OfficeDev/microsoft-teams-apps-icebreaker#88]
I could have sworn I saw an update to the app but am not able to find the link anymore... i thought a few updates were made where in it added a few "icebreaker" things for folks to ask during the meeting/scheduling... did anyone else remember seeing this?

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
