### ISSUE TITLE
How to be cost effective with Icebreaker?

### ISSUE THREAD

**Issue by trle1994** [OfficeDev/microsoft-teams-apps-icebreaker#89]
Hello,

I have the app trigger match once every 2 weeks, but each day it charges me more and more which I think can be excessive. Is there a way to save money to avoid it from incurring charge when not being used?

**Comment by gdherbert** [comment]
I set the machine to a F1 (instead of the default S1) in Icebreaker App Service Plan, Scale Up. This drops ths cost considerably with 60 minutes compute a day for free.

**Comment by chartaam** [comment]
Thanks for this suggestion. I've made this change on my two instances, and hope to see the cost savings!
