### ISSUE TITLE
Analytics on Matches/Pauses?

### ISSUE THREAD

**Issue by RobCRees** [OfficeDev/microsoft-teams-apps-icebreaker#94]
Is there a way to report on how many users are pausing matches?

Is there a way to see who is using this tool?

Thanks,
Robert

**Comment by chartaam** [comment]
There is some documentation about Telemetry here: https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/wiki/Telemetry
But I don't know enough about Analytics to really figure out how to get a good report.
(If you know how, please share for the rest of us!)

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
