### ISSUE TITLE
Change Day of The Week?

### ISSUE THREAD

**Issue by RobCRees** [OfficeDev/microsoft-teams-apps-icebreaker#95]
I did this before... but cannot figure out how to change the day of the week our meeting occurs, can someone please help me?

I want to change our weekly day to Monday at 10am.

Thanks,
Robert

**Comment by ValeriaQuests** [comment]
@RobCRees, pairing is set in Azure Deployment template.

**Comment by ValeriaQuests** [comment]
I haven't found in Azure AppService settings how to change Pairings day/time without re-deployment, But looks like, Logic App designer can help with that: https://blog.thoughtstuff.co.uk/2019/07/how-to-adjust-the-pairing-schedule-of-the-icebreaker-bot-teams-app-template/

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
