### ISSUE TITLE
Tracking number of users who start a chat

### ISSUE THREAD

**Issue by taeyh** [OfficeDev/microsoft-teams-apps-icebreaker#96]
Hi, is there a way we are able to track the telemetry on Application Insights for the number of users who click the "Chat with *name*" or "Propose meetup" option on the Icebreaker card?

**Comment by chartaam** [comment]
There is some documentation about Telemetry here: https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/wiki/Telemetry
But I don't know enough about Analytics to really figure out how to get a good report.
(If you know how, please share for the rest of us!)

**Comment by v-royavinash** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
