### ISSUE TITLE
How to create different matching cadence (logic app) for different Icebreaker groups?

### ISSUE THREAD

**Issue by trle1994** [OfficeDev/microsoft-teams-apps-icebreaker#97]
Hello,

I'm currently running the Icebreaker bot in different teams, however, the logic app cadence is the same for both. How do I create different recurrences for different teams?

**Comment by lostdoco** [comment]
https://blog.thoughtstuff.co.uk/2019/07/how-to-adjust-the-pairing-schedule-of-the-icebreaker-bot-teams-app-template/

**Comment by chartaam** [comment]
We also need to have different Teams have different notification schedules and frequencies. I would love to know how to do this.

(The link shows how to change it, not how to have different ones for different teams.)

**Comment by chartaam** [comment]
There is more info here: https://github.com/OfficeDev/microsoft-teams-apps-icebreaker/issues/74
